### ISSUE TITLE
stub/mock a version

### ISSUE THREAD

**Issue by rismoney** [majkinetor/au#115]
I have a use case which may be able to be addressed with streams, but I tend to think it's not quite the right fit (adds complexity, when I am not really maintaining multiple versions, but rather out of sequence releases).    

Example:
Package foo 2.0 is the latest, but a version 1.9 needs to be created due to user request.  It's a 1-off operation.

I can manually modify nuspec to 1.9 but then the next invocation of AU will attempt a 2.0 upgrade .  In this case I get an upgrade commit to the repo.  But technically, I don't need 1.   HEAD version in this scenario is not relevant.

Ideally what I would like is to edit nuspec to 1.9, choco pack, and push.  In addition to editing nuspec save a latestversion.txt that if detected by au, references that version, instead of the value learned in nuspec, essentially become a per package "latest override" detector.   Then when 2.1 comes out, I can delete the latestversion.txt and simply edit the nuspec to 2.1.

My goal in this particular scenario, is to have a precise audit history in git, that properly portrays the intentions of the user adding an interim release, that isn't "managed" the way streams are.

Does this make sense?

**Comment by rismoney** [comment]
Maybe a better term is version locking or pinning.

**Comment by rismoney** [comment]
it might be trivial-
```
if (Test-Path versionmock.txt) {
  $v = Get-Content versionmock.txt
}
else
  ...
}       
```

**Comment by majkinetor** [comment]
This can't be solved by version alone (except in special cases) as it also requires to specify desired URLs and perhaps other latest data. 

Besides, you can already use an `$au_Version` to override version in a way you describe it.

**Comment by majkinetor** [comment]
Also, you can create BeforeEach block in updateall Options to implement this exact logic. I am planning to work on plugins that can be run between packages too in the future.

**Comment by rismoney** [comment]
> Besides, you can already use an $au_Version to override version in a way you describe it.

How?  Do I need to add logic in global:au_GetLatest?  Trying to undertstand the mechanics on how to use this variable.

**Comment by majkinetor** [comment]
`$au_Version` is set externally, which means it will be available as global var. If you do nothing package will be forced to use that version. You could also act on it.
