### ISSUE TITLE
Option to move the tempfile to Packagefolder after get_checksum

### ISSUE THREAD

**Issue by FLeven** [majkinetor/au#120]
I added a online to **Update-Package.ps1** to move the temp-file after the checksum check to my project folder. This helps a lot to internalize packages. It would be nice to have a parameter to enable or disable this behavior.

**Comment by majkinetor** [comment]
Sorry, there is no incentive for me in this moment to develop things that can be used only for paid version of chocolatey.

**Comment by FLeven** [comment]
It is essentially the same as advised in your "Embedding binaries" example, but it is unnecessary to download the binary again. Get-RemoteFiles also has no progress-bar, so one might miss the second download.

**Comment by majkinetor** [comment]
`Get-RemoteFiles` should be used with `ChecksumFor none` so that files are not downloaded 2 times.
