### ISSUE TITLE
Get-RemoteFiles adds extra extention for .7z

### ISSUE THREAD

**Issue by teknowledgist** [majkinetor/au#123]
If the download file has a .7z extension, Get-RemoteFiles will add a second one.  E.G. `<basename>.7z.7z`.

This can be fixed by changing the `name4url` function.  Currently:
```
function name4url($url) {
        if ($FileNameBase) { return $FileNameBase }
        $res = $url -split '/' | select -Last 1 -Skip $FileNameSkip
        $res -replace '\.[a-zA-Z]+$'
    }
```
The `$res -replace '\.[a-zA-Z]+$'` is the issue.  It only allows for alphabetic-only character extensions.  Is that intentional?  If not, either:

    $res -replace '\.[a-zA-Z0-9]+$'

or

    $res -replace '\.[^.]+$'

could work.  However, if that is intentional (to not strip version numbers, maybe?), could an exception for 7zip-compressed files (as the most likely file type with an alpha-numeric extension) be included?:

    $res -replace '\.([a-zA-Z]+|7z)$'

Thanks.

**Comment by majkinetor** [comment]
Can you try to set up `FileNameBase` parameter in this case ?

**Comment by teknowledgist** [comment]
Sure, I guess.  

However, the comments in the code do state about the `FileNameBase` parameter:

    # Use this parameter if remote URL doesn't contain file name but generated hash.

Which is incomplete if it also doesn't work for download files with alpha-numeric extensions.

You built this excellent tool so that when the URL does not have a file name at the end, the package maintainer can assign a `FileNameBase`.  If there appears to be a file name at the end of the URL, isn't it best that the package will automatically contain the download file name that matches the URL even if the developer changes the download file name?  Why should that be different for files with alpha-numeric extensions?

Are there situations where a package maintainer needs to download a file with a version number *and* without an extension?  The specific `7z` option would still be safe then.  Since the vast majority of files to embed in a package are either executables (all of which are alphabetic-only extensions, I believe) or compressed files, the worst you would need to to is add the compression formats that 7zip handles containing digits.  (You would probably want to not include the exceedingly rare `.001` extension.) Basically:

    $res -replace '\.([a-zA-Z]+|7z|bz2|bzip2|tbz2|)$'

Anyway, this is just my humble opinion; It's your baby.  I use and appreciate it a ton, so thank you either way.

**Comment by Thilas** [comment]
I don't see any reason why not to use this proposal:

    $res -replace '\.[^.]+$'

Especially when it is precisely how extensions are determined in the `ext` function right below `name4url`:

    if ($url -match '(?<=\.)[^.]+$') { return $Matches[0] }
