### ISSUE TITLE
small typo errors

### ISSUE THREAD

**Issue by xse** [majkinetor/au#124]
Hi,
There is a small typo error in the [.EXAMPLE given here](https://github.com/majkinetor/au/blob/033dc47a05869b5f38dc010089ce998d74bc350d/AU/Public/Update-Package.ps1) for the automated documentation : 
`$download_page = Invoke-WebRequest -Uri https://github.com/hluk/CopyQ/releases`

Should be : 
`$download_page = Invoke-WebRequest https://github.com/hluk/CopyQ/releases -UseBasicParsing`

On windows when IE isn't here using this without -UseBasicParsing give the following error : 
```

 $download_page = Invoke-WebRequest -Uri https://github.com/hluk/CopyQ/releases
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:18
+ ... load_page = Invoke-WebRequest -Uri https://github.com/hluk/CopyQ/rele ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

And [on the main readme page](https://github.com/majkinetor/au/blob/master/README.md) there is a $ missing before "download_page" under the "manual checksum" section in the same au_GetLatest() function.

Have a good day !

**Comment by majkinetor** [comment]
Uninstalling IE is really not a good thing to do on Windows.
