### ISSUE TITLE
Package fix version notation is YYYYMMDD

### ISSUE THREAD

**Issue by ferventcoder** [majkinetor/au#13]
So instead of `x.y.z.20160708`, some recent packages should have been `.20160807`.

When it comes to dates, December 01 should always be higher than August 13 of the same year, and the date format notation used with YYYY MM DD reflects that when `.20161201` versus `.20160813`. Used incorrectly and then you can see the problem.

**Comment by ferventcoder** [comment]
* https://chocolatey.org/packages/dbeaver/3.7.2.20160708
* https://chocolatey.org/packages/eac/1.1.20160708
* https://chocolatey.org/packages/ampfontviewer/3.8.6.20160708
* https://chocolatey.org/packages/trid/2.20.20160708
* https://chocolatey.org/packages/nexus-oss/2.13.0.0120160708
* https://chocolatey.org/packages/wzgrapher/0.95.20160708

Let me know what you want me to do with these. It could not hurt to approve them as is for now as the day was less than the month.

What do you want to do with 
* https://chocolatey.org/packages/wkhtmltopdf/0.12.3.220160708
* https://chocolatey.org/packages/dngrep/2.8.16.020160708

**Comment by ferventcoder** [comment]
I've moved the second comment over to your Chocolatey repository so you can talk specifically about packages there.

**Comment by majkinetor** [comment]
Its like that already: https://github.com/majkinetor/au/blob/master/Update-Package.ps1#L215
If I had any mistakes in my packages those were created prior to this feature and I manually changed the version.
