### ISSUE TITLE
Allow to use custom branch name

### ISSUE THREAD

**Issue by dimqua** [majkinetor/au#131]
Since my branch name is not `master`, I get this error:
```
Executing git pull
error: pathspec 'master' did not match any file(s) known to git.
fatal: Couldn't find remote ref master
```
Is branch name hardcored?
https://github.com/majkinetor/au/blob/4916b3d42511f5d7ae026ddfdacd0c289969a11f/AU/Plugins/Git.ps1#L49

**Comment by majkinetor** [comment]
Obviously. 

You can add it among parameters, and submit PR, I will be happy to merge. You are probably the only one that will need this.
