### ISSUE TITLE
readme.md breaks nuspec's description

### ISSUE THREAD

**Issue by KageShiron** [majkinetor/au#139]
I  got to know very useful feature , `Set-DescriptionFromReadm` today.
However, someone have used `readme.me` for another purpose. So, some descrption of nuspec was broken. 

- https://github.com/palethorper/chocolatey-packages/commit/2e44a96e5fd147777b9c811783290991289fb8d7#diff-f9d5e0039f28733522bb6d07ca81f3b0
- https://github.com/kujotx/chocolatey-packages/commit/844923cbc2d815219f3b5119369df02f0ec83d7d#diff-47ce9bbdac9459bdb0ccee56ccb1e2a4

I think that it is safer to enable this feature ( and other breaking changes ) by command line option or environment variable.

**Comment by majkinetor** [comment]
You can use NoReadme or env var to disable the feature.
