### ISSUE TITLE
[Request] Wild Card Support

### ISSUE THREAD

**Issue by zero77** [majkinetor/au#141]
Can you please add support for using wild cards, for example;

``url=example.com/latest/setup-64-*.exe`` 
``name=setup-64-*.exe``

Thanks

**Comment by zero77** [comment]
With wild card.
`example.com/latest/setup-64-*.exe`

Without wild card.
`example.com/latest/setup-64-v1.12.exe`

**Comment by Thilas** [comment]
Could you be more specific? I don't understand where you would use such wildcard with AU... The whole purpose of `update.ps1` is to provide the exact information of a new version to package. Please provide a more comprehensive example.

**Comment by majkinetor** [comment]
I dont think that is possible in general case. It would be possible to search a site for links using wildcard but I dont think its  useful generally and has potential to get unrelated things.

⁣Sent from BlueMail ​

**Comment by zero77** [comment]
I see, I was just thinking along the lines of small changes in file names, like dates or version numbers that change but the rest of the file name stays the same.

Like in this case the “20180416-0512” could be replaced by a wild card, as that’s the only part that changes.
https://nightlies.videolan.org/build/win64/last/vlc-4.0.0-20180416-0512-dev-win64.exe
