### ISSUE TITLE
Getting TLS errors when uploading gist

### ISSUE THREAD

**Issue by glennsarti** [majkinetor/au#142]
Getting a `The request was aborted: Could not create SSL/TLS secure channel.` when trying to upload a gist.  Given that github HTTPS is TLS1.2 now, I suspect we need at add https://github.com/majkinetor/au/commit/4a0024dc5719852f28958d3072d868c2e87314f5#diff-0768bf9afd2c6915bb8a3f836b971d73R303 just before https://github.com/majkinetor/au/blob/cbdddc85de4ddd28e705e83707ca00dc295c7d6a/AU/Plugins/Gist.ps1#L56

https://ci.appveyor.com/project/puppetlabs/puppet-chocolatey-packages/build/46
```
...
   [1/1] puppet-agent has no updates (13.42s)
Running Report
Saving markdown report: C:\projects\puppet-chocolatey-packages\Update-AUPackages.md
Running History
Saving history to C:\projects\puppet-chocolatey-packages\Update-History.md
Running Gist
  ERROR:  
    The request was aborted: Could not create SSL/TLS secure channel.
Running Git
No package updated, skipping
Running RunInfo
 ```

**Comment by codingsteff** [comment]
i have received the same error message since february 22nd

**Comment by majkinetor** [comment]
Update ur update all ps1 according to my repo or coreteam. 

I will see to add thos to gist plugin.

**Comment by glennsarti** [comment]
For ref;
https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/update_all.ps1#L112-L115

**Comment by codingsteff** [comment]
Ok, thanks. All right.

**Comment by majkinetor** [comment]
Reference: https://githubengineering.com/crypto-removal-notice

**Comment by mlt** [comment]
I'm [getting similar message](https://ci.appveyor.com/project/PurpleI2P/chocolatey-packages#L115) while trying to (force) check a package version. It says AU is `Version              2019.5.22`. Am I missing something?
