### ISSUE TITLE
Stream support for multiple similar packages via file system

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#146]
We often have packages that reuse most of the metadata and scripts with few differences (install/portable notably, but other types exist to)

It would be useful to streamline this into single package. That would achieve:

- easier development and way easier maintenanince 
- less bugs due to DRY
- treating multiple similar packages atomically in both on and off boarding
- consistent experience across all packages
- improved discoverability

/cc @Thilas

**Comment by majkinetor** [comment]
Here is one example of handling this using AU. 

We could create directory `streams` within packages

```
mkvtoolnix
   streams
        mkvtoolnix
        mkvtoolnix.install
        mkvtoolnix.portable
```

Each stream folder could contain files to be copied to the package directories when that stream is activated and name of the stream should be taken from the folder name.

With some special syntax we could add/remove files before packaging.

```
mkvtoolnix
    -tools
    -legal
mkvtoolnix.install
    +tools\ChocolateyIntall.ps1
mkvtoolnix.portable
    +tools\ChocolateyIntall.ps1
```

So, in this case 

- mkvtoolnix is a meta so it doesn't need tools and legal stuff, just empty those folders (but keep them, or we need to fix nuspec too).
- install and portable will all use separate installers, + means that ChocolateyInstall.p1 will replace existing one or add a new one.
- all packages will use the same AU updater, Readme.md, nuspec, screenshots, icons, and anything else really. 

With this set we could have it simple in AU in a way something like:

```
au_BeforeUpdate() { Set-CurrentStream } 
au_AfterUpdate()   { Revert-CurrentStream }
```

By doing this in AU itself this could work in a magical fashion. This is not very well thoughtout at this moment, just brainstorming ideas.

**Comment by majkinetor** [comment]
Abandoning this idea. Streams are not used that much to justify such development.

**Comment by ComFreek** [comment]
What's the current best way to have two packages `pkg.install` and `pkg.portable`? Should I really duplicate folders and files?

**Comment by majkinetor** [comment]
There are several ways:

1. Duplicate files but allow some reuse (single au updater for example)
1.  Do not duplicate but put anything in the same folder, and copy files around in `au_beforeUpdate`. For example Readme.install or Readme.portable to Readme.md (similar to other files).
1. Create single chocolatey installer and updater that depends on the name of the package. This might be considered antipattern by chocolatey reviewers, but its best to ask them on this on gitter.
1. Create 2 streams but this is only making au updater solution, you still need to copy files around for stream in au_BeforeUpdate.
