### ISSUE TITLE
Bad content type for url

### ISSUE THREAD

**Issue by teknowledgist** [majkinetor/au#147]
I'm trying to make an automatic package, but it seems the website doesn't return the correct content type for the .exe download.  Basically, `au_GetLatest` returns a `URL32 = https://www.petges.lu/pubfiles/ac-900a.exe`, and I'm getting:

```
Bad content type 'text/html':https://www.petges.lu/pubfiles/ac-900a.exe
At C:\Users\syseh\Documents\WindowsPowerShell\Modules\AU\Public\Update-Package.ps1:110 char:42
+             if ($res = check_url $url) { throw "${res}:$url" } else { ...
+                                          ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Bad content typ...les/ac-900a.exe:String) [], RuntimeException
    + FullyQualifiedErrorId : Bad content type 'text/html':https://www.petges.lu/pubfiles/ac-900a.exe
```

Does AU have any way to deal with this? 

Thanks.

**Comment by teknowledgist** [comment]
I figured out how to get around it, I guess.  I added `$Global:au_NoCheckUrl = $true` at the top of the *update.ps1* file.  Is that the only/best solution?

**Comment by majkinetor** [comment]
That usually means that you need to set headers. In master branch you have a new feature for that:

* https://github.com/majkinetor/au#cant-validate-url-error


or you can handle that yourself in Powershell.

You need to find correct header yourself if that is the case, and its typically `Referer`.

If you don't embed the installer into the package, you can simply use `NoCheckUrl` option on `update` to skip this step, but I believe then you will have the same problem in ChocolateyInstall.ps1

**Comment by AdmiringWorm** [comment]
If I remember correctly, when running it through chocolatey it outputs a warning, but doesn't necessarily abort the installation as long as the file can be executed.

Could be remembering wrong though.

**Comment by teknowledgist** [comment]
@majkinetor, I don't know how I could utilize the `$Latest.Options.Headers`.  

Is it something like this in the au_GetLatest function?:
```
   return @{ 
            Version  = $version
            URL32    = $url32
            Options  = @{
                      Headers = @{
                               Referer = $(Something_I_still_need_to_figure_out)
                       }
                 }
           }
```

(I did notice that the browser handled the url differently, but I'm not sure how to translate that into automation.)

Sorry for the ignorant questions.

**Comment by majkinetor** [comment]
Yeah, that should be it. Never tried it so far tho as it was just merged. You need to make sure you use unpublished AU on master.
