### ISSUE TITLE
EXE getting embedded when using `Get-ChocolateyWebFile`

### ISSUE THREAD

**Issue by galeksandrp** [majkinetor/au#152]
Build | appveyor.yml | update.ps1
--- | --- | ---
[Build][build] | [appveyor.yml][appveyor-yml] | [update.ps1][update-ps1]

```ps1
FileFullPath           = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)\traefik.exe"
```

* `au_BeforeUpdate` not used
* `Get-RemoteFiles` not used

[build]: https://ci.appveyor.com/project/galeksandrp/au-packages/build/317
[appveyor-yml]: https://github.com/galeksandrp/au-packages/blob/1e2c55cbb913456c122870a8840c992684d5fcb7/.appveyor.yml
[update-ps1]: https://github.com/galeksandrp/au-packages/blob/1e2c55cbb913456c122870a8840c992684d5fcb7/gogs/update.ps1

**Comment by majkinetor** [comment]
Its expected in this case. Use `au_beforeUpdate  to remove the file.
