### ISSUE TITLE
Why --allow-empty?

### ISSUE THREAD

**Issue by galeksandrp** [majkinetor/au#153]
In case when [AU specific:VERSION] is used, and this version exist in Git, empty commit will be created.

https://github.com/majkinetor/au/blob/0f0c0ad1b9b7f20819975d06dd33d42a1903f77b/AU/Plugins/Git.ps1#L65
https://github.com/majkinetor/au/blob/0f0c0ad1b9b7f20819975d06dd33d42a1903f77b/AU/Plugins/Git.ps1#L81

**Comment by majkinetor** [comment]
Because we still want latest report URL
