### ISSUE TITLE
Updating dependency on forced update version

### ISSUE THREAD

**Issue by riezebosch** [majkinetor/au#154]
See: https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/issues/32. Do you have a way or advice on how to handle this? Or is this something AU should support but doesn't handle yet?

**Comment by majkinetor** [comment]
Add `$Latest.RemoteVersion` and use it in search and replace of dependency instead of `$Latest.Version` which can bi fixed by AU.
