### ISSUE TITLE
FormatEntryData is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Elderry** [majkinetor/au#157]
I installed `AU` via `Install-Module AU`, then I try to `Import-Module AU` here it comes:
```
The term 'Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\PowerShell\Modules\au\2018.5.18\AU.psm1:5 char:42
+     ls $PSScriptRoot\$path\*.ps1 | % { . $_ }
+                                          ~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.Power...FormatEntryData:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
AU version: 2018.5.18
PowerShell version: 6.0.2 Core
OS version: Windows Pro Version 1803

**Comment by AdmiringWorm** [comment]
I don't believe PowerShell Core is supported, only the full PowerShell framework.

**Comment by Elderry** [comment]
Just tested, the same thing happens on PowerShell Desktop 5.1.

**Comment by majkinetor** [comment]
This is strange. It looks like it is trying to execute `. Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData` which means that `ls $PSScriptRoot\$path\*.ps1` returned it for some strange reason.

Some other app maskarading as `ls` ?, try `gcm ls` and give output here.

**Comment by Elderry** [comment]
Now I know it, I have
```
Remove-Item Alias:ls
function ls { Get-ChildItem | Format-Wide -AutoSize -Property 'Name' }
```
in my PowerShell profile to have a Linux-style `ls`.
