### ISSUE TITLE
This package had an issue pushing: An asynchronous call is already in progress

### ISSUE THREAD

**Issue by flcdrg** [majkinetor/au#159]
Had a bunch of packages return errors from updating today..

Package: dotCover

Push ERROR
Attempting to push dotCover.2018.1.3.nupkg to https://push.chocolatey.org Failed to process request. 'This package had an issue pushing: An error occurred while executing the command definition. See the inner exception for details.'.  The remote server returned an error: (409) Conflict..

Package: dotMemory

Push ERROR
Attempting to push dotMemory.2018.1.3.nupkg to https://push.chocolatey.org Failed to process request. 'This package had an issue pushing: An asynchronous call is already in progress. It must be completed or canceled before you can call this method.'.  The remote server returned an error: (409) Conflict..

Package: microsoft-teams

Push ERROR
Attempting to push microsoft-teams.1.1.00.17553.nupkg to https://push.chocolatey.org Failed to process request. 'This package had an issue pushing: An error occurred while executing the command definition. See the inner exception for details.'.  The remote server returned an error: (409) Conflict..

Package: ReSharper

Push ERROR
Attempting to push ReSharper.2018.1.3.nupkg to https://push.chocolatey.org Failed to process request. 'This package had an issue pushing: An error occurred while executing the command definition. See the inner exception for details.'.  The remote server returned an error: (409) Conflict..

Package: resharper-clt

Push ERROR
Attempting to push resharper-clt.2018.1.3.nupkg to https://push.chocolatey.org Failed to process request. 'This package had an issue pushing: An asynchronous call is already in progress. It must be completed or canceled before you can call this method.'.  The remote server returned an error: (409) Conflict..

My repo is here - https://github.com/flcdrg/au-packages

**Comment by majkinetor** [comment]
Upstream problem, nothing I can do about it on AU level.

**Comment by flcdrg** [comment]
So it wouldn't be related to the "multithread support"?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by majkinetor** [comment]
No, its a `choco push` error.

I think we had those on core team packages several times so far, you might want to get more info there on gitter channel. 

If the error doesn't repeat, then ignore it. If it does, I think people like @gep13 would be in the best position to help understand the origin of the problem.
