### ISSUE TITLE
Incorrect stream version for updated package displayed in progress

### ISSUE THREAD

**Issue by flcdrg** [majkinetor/au#160]
Not a big problem, but the latest run for updating a package that is using streams listed in the log that it had updated the lowest stream number package, but in fact it had updated (and submitted) a higher version.

This build log - https://ci.appveyor.com/project/DavidGardiner/au-packages/build/521 contains:
 "[25/26] ubiquiti-unifi-controller is updated to 5.4.19 and pushed (37.23s)"

But actually it was v5.8.24 that was pushed.

My repo is here if that's relevant https://github.com/flcdrg/au-packages

**Comment by majkinetor** [comment]
Yeah, that is known issue, not reported here tho.

**Comment by majkinetor** [comment]
Not only in progress, in report, git releases, everywhere really.

**Comment by Thilas** [comment]
I'll work on something to fix this.

**Comment by AdmiringWorm** [comment]
@majkinetor it looks like the git releases plugins get the correct version:
https://github.com/chocolatey/chocolatey-coreteampackages/releases/tag/gitextensions-2.51.4
https://github.com/chocolatey/chocolatey-coreteampackages/releases/tag/gitextensions-2.51.4

or perhaps @Thilas already fixed this issue?

**Comment by Thilas** [comment]
I don't remember exactly but I might have fixed this a while ago. For the current bug I hope I'll find time this weekend to work on it. I'll let you know.
