### ISSUE TITLE
check_url fails for specific FTP server

### ISSUE THREAD

**Issue by ComFreek** [majkinetor/au#161]
(This seems to be more of a PowerShell issue than an AU issue.)

The following code fails:
```
function global:au_GetLatest {
  # ...
  return @{ Url32 = 'ftp://wa651f1:anonymous@mh-nexus.de/HxDSetup.zip'; Version = $version }
}
```
Error message (translated): <pre>PS P:\chocolatey\my-packages\hxd> .\update.ps1
hxd - checking updates using au version 2018.1.11

URL check
Can't validate URL
Exception when calling "Close" with 0 argument(s):  "The underlying connection has been closed.:
Unknown error while receiving..":ftp://wa651f1:anonymous@mh-nexus.de/HxDSetup.zip
In C:\Program Files\WindowsPowerShell\Modules\au\Public\Update-Package.ps1:110 Column:42
+             if ($res = check_url $url) { throw "${res}:$url" } else { ...
+                                          ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Can't validate ...de/HxDSetup.zip:String) [], RuntimeExcepti
   on
    + FullyQualifiedErrorId : Can't validate URL</pre>

[`check_url`](https://github.com/majkinetor/au/blob/ab7ac5ee4af4ba0eb7149db0294025249e45e50c/AU/Private/check_url.ps1#L2) calls [`request`](https://github.com/majkinetor/au/blob/ab7ac5ee4af4ba0eb7149db0294025249e45e50c/AU/Private/request.ps1#L1) which in turn uses `System.Net.WebRequest`. I can reproduce the problem with the FTP server using the code below:

```powershell
[System.Net.WebRequest]::Create('ftp://wa651f1:anonymous@mh-nexus.de/HxDSetup.zip').GetResponse()
```

Note that using `System.Net.WebClient` works, though:
```powershell
$client = New-Object System.Net.WebClient
$client.DownloadString('ftp://wa651f1:anonymous@mh-nexus.de/HxDSetup.zip')
```

The error message from the `[System.Net.WebRequest]::Create` code (translated):

<pre>Exception when calling "GetResponse" with 0 argument(s): "Connection to remote server could not be established"
In line:1 column:1
+ [System.Net.WebRequest]::Create('ftp://wa651f1:anonymous@mh-nexus.de/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException</pre>

Note that this error seems to only occur with this specific FTP server. E.g. with another [publicly accessible FTP server](https://stackoverflow.com/a/40135344/603003) it works:

```powershell
[System.Net.WebRequest]::Create('ftp://demo:password@test.rebex.net/readme.txt').GetResponse()
```

**Comment by majkinetor** [comment]
There will always be specific case that defaults do not cover. That was one of the main reasons to use Powershell in AU so that you can circumvent such cases.

So, in this case, just disable check, and do it yourself the way you find working in beforeUpdate.
