### ISSUE TITLE
All update checks failing with 'Can't validate URL'

### ISSUE THREAD

**Issue by flcdrg** [majkinetor/au#166]
Nightly appveyor build failed for https://github.com/flcdrg/au-packages this morning for every package with errors like the following:

     Parameter name: name":https://download.jetbrains.com/resharper/ReSharperUltimate.2018.2.EAP8/JetBrains.ReSharperUltimate.2018.2.EAP8.Checked.exe (6.41s)
   [2/28] beyondcompare ERROR: 
     Can't validate URL 
 
     Parameter name: name":https://www.scootersoftware.com/BCompare-fr-4.2.6.23150.exe (14.18s)
   [3/28] dellcommandupdate ERROR: 
     Can't validate URL 

I'm using master for au - maybe that latest commit is relevant?

**Comment by flcdrg** [comment]
As a workaround, I've updated my appveyor.yml file to pin to 2018.5.18 instead of master

**Comment by majkinetor** [comment]
Fixed, sorry for the problem.

**Comment by jack1142** [comment]
It's caused by commit for issue #164.
