### ISSUE TITLE
Updating URLs from a Github release page hangs

### ISSUE THREAD

**Issue by joachimschmidt557** [majkinetor/au#167]
Most of my automatically updated packages query their latest binaries from GitHub releases. When AppVeyor tries to update all packages, all these packages fail to update and hang completely until the `1200s UpdateTimeout` is reached. This problem does not occur when the website queried is not GitHub.

![image](https://user-images.githubusercontent.com/28556218/45599321-a285db00-b9e9-11e8-86ae-6672cc72774f.png)

I think this problem is related to the TLS used on the GitHub website.

My repository: https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic
My update status: https://gist.github.com/joachimschmidt557/8a2f24b529db5159a7c189c3b4ccd9a4
My AppVeyor builds: https://ci.appveyor.com/project/joachimschmidt557/chocolatey-packages-manual-automatic

**Comment by majkinetor** [comment]
What happens if you add `-UseBasicParsing` to the `iwr` in au_getlatest.

**Comment by joachimschmidt557** [comment]
Yes, this works. Thank you!
