### ISSUE TITLE
Job returned no object, Vector smash

### ISSUE THREAD

**Issue by JamieMagee** [majkinetor/au#173]
I'm having issues creating a new AU package for jetty. [These](https://github.com/JamieMagee/chocolatey-packages/tree/master/jetty) are my chocolatey/au scripts and this is [the relevant output from my Appveyor build](https://ci.appveyor.com/project/JamieMagee/chocolatey-packages#L117).

I'm struggling a little bit to see what the error is, as it works locally, but not on Appveyor, and the error message is a little bit cryptic.

**Comment by majkinetor** [comment]
Try without UBP param to Invoke-WebRequest or use some other way to download file in this case.

**Comment by JamieMagee** [comment]
I tried without `-UseBasicParsing`, and I got the same error message. I tried with `System.Net.Webclient`, and I get the [error message](https://ci.appveyor.com/project/JamieMagee/chocolatey-packages#L116)

>Cannot bind argument to parameter 'Path' because it is null. (3.20s)

Is there anything obvious that's wrong with my package, or update script?

**Comment by majkinetor** [comment]
You cant use links without iwr.

Test this locally, you must change the parsing with web client to use text searching instead.

**Comment by JamieMagee** [comment]
Okay, I've [updated it to parse the HTML text correctly](https://github.com/JamieMagee/chocolatey-packages/commit/32d4bfa1c0cfaf906baa88e749a3516d2a854850), but now I'm back to the [original error message](https://ci.appveyor.com/project/JamieMagee/chocolatey-packages/builds/21011254#L121)

>Job returned no object, Vector smash ?

**Comment by AdmiringWorm** [comment]
@JamieMagee looking at the logs you have as artifacts on appveyor, it seems like the failure happens during the automated checksum grabbing.

I would suggest testing to calculate the hash manually instead (well semi-manually).

Change your update.ps1 script to the following (I'm using the version you used iwr)
```powershell
import-module au

$releases = 'https://www.eclipse.org/jetty/download.html'

function global:au_BeforeUpdate {
  $Latest.ChecksumType32 = 'sha256' # You can change this to whatever you want
  $Latest.Checksum32 = Get-RemoteChecksum -Url $Latest.URL32 -Algorithm $Latest.ChecksumType32
}

function global:au_SearchReplace {
  @{
    ".\tools\chocolateyInstall.ps1" = @{
      "(?i)(^\s*url\s*=\s*)('.*')"      = "`$1'$($Latest.URL32)'"
      "(?i)(^\s*checksum\s*=\s*)('.*')" = "`$1'$($Latest.Checksum32)'"
    }
  }
}

function global:au_GetLatest {
  $download_page = Invoke-WebRequest -Uri $releases -UseBasicParsing

  $url = $download_page.links | Where-Object href -match '^.*.zip$' | ForEach-Object href | Select-Object -First 1
  $zip = ((Split-Path $url -Leaf) -split "-")[2]
  $version = $zip.Substring(0, $zip.Length - 4).Replace('v', '')

  @{
    URL32   = $url
    Version = $version
  }
}

update -ChecksumFor none # Remember to change this to 'none'
```

**Comment by majkinetor** [comment]
If that doesn't work, you really shouldn't use COM objects but just parse the text for URL :) There are few examples out there I can dig up if you need some help with that.

**Comment by JamieMagee** [comment]
@AdmiringWorm [Calculating the hash manually works](https://ci.appveyor.com/project/JamieMagee/chocolatey-packages). I'm not sure what the root cause is, but if it works...

@majkinetor & @AdmiringWorm thank you for all your help :)

**Comment by AdmiringWorm** [comment]
@JamieMagee I believe the root of the cause is the installation of the environment variable in the install script (I'm not 100% sure about that though).

**Comment by AdmiringWorm** [comment]
Anyways, glad you managed to get it working though
