### ISSUE TITLE
Test-Package unable to handle my pre-release package version

### ISSUE THREAD

**Issue by TraGicCode** [majkinetor/au#176]
When running Test-Package cmdlet on my ravendb chocolatey package with a pre-release version i'm noticing it's dropping the "r" off my package name as shown in the following log output below:

```powershell
Testing package install
Installing the following packages:
ravendb.4.1.4-patch-41009.nupkg
By installing you accept licenses for the packages.
'avendb.4.1.4-patch-41009' is not a valid version string.
Parameter name: version
```

**Comment by majkinetor** [comment]
Just replace second `-` with something else, i.g. `ravendb.4.1.4-patch_41009.nupkg`

**Comment by majkinetor** [comment]
The double - doesn't seem valid pre-release version according to nuget specification.

https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages
