### ISSUE TITLE
How to download a binary sent via an octet-stream flow generated by a php script?

### ISSUE THREAD

**Issue by chtof** [majkinetor/au#184]
Hi,

On https://www.raidrive.com/download/, a Download button/link redirects to https://www.raidrive.com/download.latest.php and open directly a popup to download the installer "RaiDrive_1.6.2.416.exe".

- Get-RedirectedUrl doesn't give another URL.
- When I use Invoke-WebRequest to download https://www.raidrive.com/download.latest.php, I download the download page.

Do you have an idea how I can download this binary in my update.ps1 (embedded package)?

Below, please find what happens (using the developer tools) when I download the file (I have highlighted more important information):

```
> **Request URL: https://www.raidrive.com/download.latest.php**

Request Method: GET
Status Code: 200 OK
Remote Address: 40.118.202.40:443
Referrer Policy: no-referrer-when-downgrade
Cache-Control: must-revalidate
Connection: Keep-Alive
Content-Description: File Transfer

> **Content-Disposition: attachment; filename="RaiDrive_1.6.2.416.exe"**

Content-Length: 23814808

> **Content-Type: application/octet-stream**

Date: Tue, 14 May 2019 22:21:44 GMT
Expires: 0
Keep-Alive: timeout=5, max=100
Pragma: public
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.24
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: _icl_visitor_lang_js=en-us; wpml_browser_redirect_test=0
Host: www.raidrive.com
Referer: https://www.raidrive.com/download/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
```

**Comment by majkinetor** [comment]
If you F12 when you click download, you can right click and select an option to export as curl.
This is what I get

`curl "https://www.raidrive.com/download.latest.php" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" -H "DNT: 1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3" -H "Referer: https://www.raidrive.com/download/" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-US,en;q=0.9,sr;q=0.8,hr;q=0.7,de;q=0.6,bs;q=0.5,la;q=0.4,da;q=0.3" -H "Cookie: _icl_visitor_lang_js=en-us; wpml_browser_redirect_test=0" --compressed
`

There you can cherry pick what works. Its usually referrer:

`iwr https://www.raidrive.com/download.latest.php -Headers @{Referer = 'https://www.raidrive.com/download/'} -OutFile ra_setup.exe`

**Comment by chtof** [comment]
It works, thanks a lot for this wonderful answer, for the explanation and for the tip!
