### ISSUE TITLE
Is it possible to ignore stream ?

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#185]
Returning `ignore` from `au_GetLatest` will ignore all streams. Is it possible now to ignore one stream ? Perhaps as 

```
@ {
   stream1 = @{...}
   stream2 - 'ignore'
}
```

**Comment by Thilas** [comment]
I'll have a look and let you know about this.

**Comment by Thilas** [comment]
I confirm that "ignore" is supported for streams. I added some new tests to illustrate that in #186.

**Comment by majkinetor** [comment]
Nice. Thanks.
