### ISSUE TITLE
Strange download install error on update

### ISSUE THREAD

**Issue by teknowledgist** [majkinetor/au#187]
I have an embedded package, marcedit that is giving me a strange result when I attempt to update:
````
PS marcedit> .\update.ps1
marcedit - checking updates using au version 2018.5.18

URL check
  https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup64Admin.msi
  https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup32Admin.msi
nuspec version: 7.1.150
remote version: 7.1.170
New version is available
Automatic checksum started
Installing 32-bit chocolatey\marcedit...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could
 mean a pending reboot is necessary prior to install or something else (like the same version is already installed).
Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v
c:\chocolatey\marcedit_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the
error.
````

Why is it attempting to install??  

The `chocolateyinstall.ps1` is super generic, and the only thing the `update.ps1` does that is the slightest bit different is post a warning in the `global:au_BeforeUpdate()` function about manual checksum gathering.  This is because the download site for this doesn't properly identify the file size.  `Get-RemoteFiles` is immediately returning even though the download is still ongoing and any checksum is totally wrong.  That is an issue with the website that negatively affects Chocolatey, but how can that problem cause an attempted install (of an incomplete download) in AU??

Is there a way to slip in a `start-sleep` command between the attempt to download and the attempt to gather checksums?  Yes, it's very artificial and kludgy, but it is for my own sanity, and users would never need to deal with it.

Thanks.

**Comment by majkinetor** [comment]
> Why is it attempting to install??

It uses installer to obtain files in order to do *Automatic checksum*. 

Anyway, this wont work based on the stuff you do in `chocolateyInstall.ps1`. This is definitely NOT a typical package. 

You should:

- Add `-ChecksumFor none` to prevent automatic checksum. This cant work in your case as you want to execute a local file, and automatic checksum expects download from the net.
- Use some other method to download a file in `au_BeforeUpdate` for example `curl.exe` works for me. However, `Get-RemoteFiles` also works for me:

```
> $Latest = @{
    Version = $version
    URL32 = 'https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup32Admin.msi'
    URL64 = 'https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup64Admin.msi'
}

> Get-RemoteFiles
Downloading to MarcEdit_Setup32Admin_x32.msi - https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup32Admin.msi
Downloading to MarcEdit_Setup64Admin_x64.msi - https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup64Admin.msi

> ls .\tools\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         6/4/2019     10:24       35611136 MarcEdit_Setup32Admin_x32.msi
-a----         6/4/2019     10:24       35611136 MarcEdit_Setup64Admin_x64.msi
```

curl.exe also downloads it and shows the size:

```
> curl.exe "https://marcedit.reeset.net/software/marcedit7/MarcEdit_Setup32Admin.msi"  --output out.msi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 33.9M    1  575k    0     0   327k      0  0:01:46  0:00:01  0:01:45  327k
```

**Comment by teknowledgist** [comment]
> It uses installer to obtain files in order to do Automatic checksum.

While I understood the underlying problem here, I was confused by the `Installing 32-bit chocolatey\marcedit...` line.  I don't see that with any other package updates.  That's what is/was "strange".

> However, Get-RemoteFiles also works for me

Well, I never said that get-remoteFiles doesn't work.  😉  It's just that in this case, Chocolatey (and AU) don't wait for it to complete before trying to grab the checksums.  I don't need it to work for an install because it's embedded, but I wasn't sure how to separate the download and the checksums (or pause between them) for the update.  

Your suggestion worked great and I managed to figure out how to grab the checksums to fully automate it.  Thanks.
