### ISSUE TITLE
Set-DescriptionFromReadme overwrites other replacements in nuspec

### ISSUE THREAD

**Issue by ComFreek** [majkinetor/au#192]
Consider my `update.ps1`:

```powershell
Import-Module au

function global:au_AfterUpdate ($Package)  {
	Set-DescriptionFromReadme $Package
}

function global:au_SearchReplace {
	@{
		'au_bug.nuspec' = @{
			"<version>[^<]*</version>" = "<version>$($Latest.version)</version>";
			"<releaseNotes>[^<]*</releaseNotes>" = "<releaseNotes>$($Latest.releaseNotesUrl)</releaseNotes>"
		}
	}
}


function global:au_GetLatest {
	return @{
		version          = '1.0.0';
		releaseNotesUrl  = "https://example.com/?random-here=$(Get-Random)";
		url32            = 'https://github.com/majkinetor/au/archive/master.zip'
	}
}

Update-Package -ChecksumFor None
```

Running `$au_Force = $true ; .\update.ps1` in PowerShell does *not* update the <releaseNotes> tag in the nuspec. However, if I comment out `Set-DescriptionFromReadme $Package`, then it works.

## How to reproduce

1. `git clone https://github.com/ComFreek/au-bug-2019-08-07.git`
2. Open `au_bug.nuspec` in editor
3. Run `$au_Force = $true ; .\update.ps1` in PowerShell
4. See if `au_bug.nuspec` changed in `<releaseNotes>` tag

**Comment by majkinetor** [comment]
Does something change if you add `-NoReadme` flag to `Update-Package` as mentioned in the docs ?

**Comment by majkinetor** [comment]
BTW, why do you do this ? Setting the readme is automatic, this line is intended to be used only if defaults are not good enough for you.

**Comment by ComFreek** [comment]
> Does something change if you add -NoReadme flag to Update-Package as mentioned in the docs ?

So if I add this to the code in my first comment, then no, nothing changes. If I add it to the code below, again nothing changes.

> BTW, why do you do this ? Setting the readme is automatic, this line is intended to be used only if defaults are not good enough for you.

Oh, I did not know it was the default behavior. Thanks for mentioning. Still, the following code does not insert the release notes URL:

```powershell
Import-Module au

function global:au_SearchReplace {
	@{
		'au_bug.nuspec' = @{
			"<version>[^<]*</version>" = "<version>$($Latest.version)</version>";
			"<releaseNotes>[^<]*</releaseNotes>" = "<releaseNotes>$($Latest.releaseNotesUrl)</releaseNotes>"
		}
	}
}


function global:au_GetLatest {
	return @{
		version          = '1.0.0';
		releaseNotesUrl  = "https://example.com/?random-here=$(Get-Random)";
		url32            = 'https://github.com/majkinetor/au/archive/master.zip'
	}
}

Update-Package -ChecksumFor None
```

I reflected this in my repo in case you want to test it: https://github.com/ComFreek/au-bug-2019-08-07.git

**Comment by majkinetor** [comment]
Ah, I thought you write about tag description, not releaseNotes. Sorry, didn't see that.

Not sure what is wrong with your code, but looks like RE is badly done, and CBB to check now via your repository. How about you use my template which works on number of packages ?

https://github.com/majkinetor/au-packages/blob/master/_template/update.ps1#L18-L20

**Comment by ComFreek** [comment]
Thank you! It's working now with these adjustments:

- Do **not** do `Set-DescriptionFromReadme $Package` in `global:au_AfterUpdate`. Instead, realy on default behavior of `Update-Package`. Namely, per default it sets the README accordingly from README.md.

- Be sure to open a new PowerShell shell if you experiment with your `update.ps1` and/or AU configuration. It seems to persist some state in your shell *across* AU calls!

**Comment by majkinetor** [comment]
The function should work in AfterUpdate. The very same function is called internally by default.

Yes, AU doesn't clean shell environment as you may want to experiment in shell with ad-hoc functions and calls. That sometimes harm, but its benefit most of the time.
