### ISSUE TITLE
Need to pass HTTP/HTTPS headers used for retrieving url/url64bit to $Latest.Options.Headers

### ISSUE THREAD

**Issue by chtof** [majkinetor/au#196]
> Can't validate URL error
> If you encounter Can't validate URL error like
> 
> Can't validate URL
> Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (401) Unauthorized.":<url>
> you need to pass HTTP/HTTPS headers used for retrieving url/url64bit to $Latest.Options.Headers as Hashtable, where key is header name, and value are header itself. This may be Authorization or Referer header or any others.

Do you have a such example please?
virtualmidisynth needs to precise referer to be downloaded:
`invoke-webrequest -uri https://coolsoft.altervista.org/en/system/files/CoolSoft_VirtualMIDISynth_2.7.3.exe -headers @{"Referer"="https://coolsoft.altervista.org/en/virtualmidisynth"}`

In au_GetLatest, I have added at the end of the function:
```
   return @{
        Version  = $matches.Version
        Options  =  @{Headers = @{ Referer = 'https://coolsoft.altervista.org/en/virtualmidisynth' }}     
        URL32    = $url.href
    }
```
It doesn't work, each time I have "Bad content type 'text/html':https://coolsoft.altervista.org/download/CoolSoft_VirtualMIDISynth_2.7.3.exe".

Could I pass headers as I am trying to do in the au_GetLatest function (in that case, where am I wrong?) or are we obliged to download the file in the au_BeforeUpdate function using invoke-webrequest and headers switch?

**Comment by majkinetor** [comment]
Passing referer should work, but in any case you can ignore default behavior and just do it yourself via `au_BeforeUpdate` if for some reason it doesn't.

I personally do not have any such examples, it was a feature done for others who requested it as I always use embedded packages.

**Comment by majkinetor** [comment]
Closing as there is no further feedback and it looks like this feature works for others.

**Comment by majkinetor** [comment]
It turns out this was not working with `Get-RemoteFiles`, but only for automatic checksum. It should work now with NEXT version.

**Comment by majkinetor** [comment]
Example: https://github.com/majkinetor/au-packages/blob/master/furmark/update.ps1#L34
