### ISSUE TITLE
Update multiple packages via a single update.ps1

### ISSUE THREAD

**Issue by rismoney** [majkinetor/au#199]
Good morning.

I have a particular package, for conversation sake lets call it office365 (chosen for simple dialog).  I also have a package office365-visio.   They both share the same binaries.   Historically I have maintained these 2 packages separately.  I am trying to make them work as a single package to conserve on disk space (as there are many more packages ie office365-publisher).

I have read the guidance on metapackages where you you essentially determine whether or not the package has been dotsourced and then dot source it from the caller package.  This scenario I think is slightly different, as the binaries backing the files are the same, I just want to handle additional search and replacing across packages:

from office365 update.ps1
```powershell
function global:au_SearchReplace {
    @{
        'tools\chocolateyInstall.ps1' = @{
                  "(^\s*url\s*=\s*)('.*')"      = "`$1'$($Latest.internalsite)'"
          "(^\s*checksum\s*=\s*)('.*')" = "`$1'$($Latest.checksum)'"
        }
        '..\office365-visio\office365-x64-visio.nuspec' = @{
          "(\<version\>).*?(\</version\>)" = "`${1}$($Latest.Version)`$2"
        }
                '..\office365-visio\tools\chocolateyInstall.ps1' = @{
          "(^\s*url\s*=\s*)('.*')"      = "`$1'$($Latest.internalsite)'"
          "(^\s*checksum\s*=\s*)('.*')" = "`$1'$($Latest.checksum)'"
        }
    }
}
```

The problem I experience with this solution is that I believe the git plugin specifically, and other post processing code pieces determines what packages are run based on the object
$Info.result

My question is essentially can I easily add an additional package item (office365-visio) to this object within the office365 update.ps1?

I don't think I want office365-visio to have an update.ps1 at all because I don't want it to do anything indepdently.

I welcome your expertise and thoughts.

**Comment by majkinetor** [comment]
This should be possible, but I need to see sources.

**Comment by rismoney** [comment]
I actually have this sample open sourced here

https://github.com/chocolatey-community/chocolatey-package-recipes/blob/master/office365-x64/update.ps1

**Comment by majkinetor** [comment]
What is the other one that uses it ?

**Comment by rismoney** [comment]
There is none yet -  Thats what I want to understand :)   the ability to update a package without an update.ps1

**Comment by rismoney** [comment]
1. package2 cannot be updated until package1 is updated 
2. package1 cannot be updated without also updating package2

only package1 has a getlatest, beforeupdate.
package1 currently performs a search and replace across 2 packages

issue is package2 doesnt get added/pushed (only search and replaced properly) because package2 isn't in $info.result and doesn't have it's own update.ps1 calling Update-Package

Hopefully clears this up.

**Comment by majkinetor** [comment]
So, you need to have 1 update.ps1 and in it return something like this:

```
function global:au-GetLatest {
    ....
     return @{ streams = [ordered]@{
        office365_visio = @{ PackageName =, Version = ... URL = ... }
        office365_xyz   = @ { PackageName =, .... }
    }}
}
```

Streams will be handled in json file which you must manually add to the repo in order for it to work on AppVeyor later.

Both streams will share other AU functions and you can select for any of them using `$Latest.PackageName` just like I did [here](https://github.com/majkinetor/au-packages/blob/master/postgresql/update.ps1#L9) where I do 1 S&R for 1 packagename and other S&R for all other. Notice that streams can share package name ( in my case I have 12,11,10,9 streams for virtual package postgresql and all streams again for postgresql12 .. postgresql9 packages).

You can do similar in au_BeforeUpdate if all packages share the same files, but keep in mind that only streams that are updated will run. For example if B stream depend on A stream getting some data but A didn't run as it wasn't updated then B will not have that data. If A is always run before B (if they are both updated remotelly) then that wont happen.
