### ISSUE TITLE
Forcing version by commit message didn't work

### ISSUE THREAD

**Issue by jgeorgeson** [majkinetor/au#203]
My package repo, commit in question: https://github.com/jgeorgeson/chocolatey-packages/tree/2a0e949422459c9cc9284101cd761982fa3e4bda

Build log for commit: https://ci.appveyor.com/project/jgeorgeson/chocolatey-packages/builds/30219087

I had recently had some trouble with pushes to chocolatey.org failing and got stuck where the package source was up-to-date with upstream and chocolatey.org but the package hadn't actually been pushed, so I had set `NoCheckChocoVersion = $true`. Would the cause the version specific in my commit message to be ignored? Or is there extra code I need to put in my `update.ps1` to make forced package versions work?

**Comment by majkinetor** [comment]
From your log artifact 

```
jfrog-cli - checking updates using au version 2019.5.22

nuspec version: 1.32.4
remote version: 1.33.1
New version is available
Automatic checksum skipped
Setting package description from README.md
Updating files
  $Latest data:
    Checksum64                (String)     dea11a07608572b1ad4085d8bf9f40f629feee50bfd37063d85d23283cd118f9
    FileType                  (String)     exe
    NuspecVersion             (String)     1.32.4
    PackageName               (String)     jfrog-cli
    URL64                     (String)     https://dl.bintray.com/jfrog/jfrog-cli-go/1.33.1/jfrog-cli-windows-amd64/jfrog.exe
    Version                   (String)     1.33.1
  jfrog-cli.nuspec
    setting id: jfrog-cli
    updating version: 1.32.4 -> 1.33.1
  .\tools\chocolateyInstall.ps1
    (?i)(^\s*url64bit\s*=\s*)('.*')     = $1'https://dl.bintray.com/jfrog/jfrog-cli-go/1.33.1/jfrog-cli-windows-amd64/jfrog.exe'
    (?i)(^\s*checksum64\s*=\s*)('.*')   = $1'dea11a07608572b1ad4085d8bf9f40f629feee50bfd37063d85d23283cd118f9'
Attempting to build package from 'jfrog-cli.nuspec'.
Successfully created package 'C:\projects\chocolatey-packages\jfrog-cli\jfrog-cli.1.33.1.nupkg'
Package updated
Chocolatey v0.10.15
Attempting to push jfrog-cli.1.33.1.nupkg to https://push.chocolatey.org
jfrog-cli 1.33.1 was pushed successfully to https://push.chocolatey.org
```

Looks like upstream problem. Maybe chocolatey team can look into it  (/cc @AdmiringWorm @gep13 )

**Comment by jgeorgeson** [comment]
I'm taking upstream here to mean jFrog, the software vendor. Is that what you had intended?

I hadn't rebuilt my package in time between the 1.33.0 and 1.33.1 releases from jFrog, so I was trying to force a package build of 1.33.0, then was going to trigger my AppVeyor job to let it automatically update from 1.33.0 to 1.33.1. But the AppVeyor build that ran from my empty commit with the forced package:version message skipped 1.33.0

IThe `remote version: 1.33.1` in my log, and related output under `Updating files` is from my [update.ps1](https://github.com/jgeorgeson/chocolatey-packages/blob/2a0e949422459c9cc9284101cd761982fa3e4bda/jfrog-cli/update.ps1) is it not? Is there something I need to put in that file, or in [appveyor.yml](https://github.com/jgeorgeson/chocolatey-packages/blob/2a0e949422459c9cc9284101cd761982fa3e4bda/.appveyor.yml) or [update_all.ps1](https://github.com/jgeorgeson/chocolatey-packages/blob/2a0e949422459c9cc9284101cd761982fa3e4bda/update_all.ps1), to support the commit-message forced versions with au+AppVeyor?

**Comment by majkinetor** [comment]
That makes more sense now. 

Unfortunatelly, fore can't be used when there is new version, which will always override it.  Even if it did work that way, you would still get latest version via your provided latest method.

Your situation is best fixed with some AU/manual combination and local push.
