### ISSUE TITLE
Consider remove SSL 3.0 form SecurityProtocol in Update-Package

### ISSUE THREAD

**Issue by xa0082249956** [majkinetor/au#206]
From <https://github.com/PowerShell/PowerShell/issues/7474>, SSL 3.0 was deprecated and **won't be supported** by PowerShell Core.

So we should consider remove SSL 3.0 from [System.Net.ServicePointManager]::SecurityProtocol in Update-Package.ps1:
https://github.com/majkinetor/au/blob/43a70862deace4f4d7ade70f7b893bc445671def/AU/Public/Update-Package.ps1#L384

Releated issue: <https://github.com/majkinetor/au/issues/158>

**Comment by jetersen** [comment]
The proper fix is https://gist.github.com/jetersen/0ac37e3f684947889d53cccb7391a9c5 based om https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-a-net-framework-version-earlier-than-47

**Comment by majkinetor** [comment]
That is not x-platform.

**Comment by jetersen** [comment]
Should be mentioned this only applies to Windows Powershell v5 and below.

**Comment by javydekoning** [comment]
I think I'm running into this issue as well. Trying to run `updateall` on `7.0.3` I get `Exception setting "SecurityProtocol": "The requested security protocol is not supported."`

**Comment by majkinetor** [comment]
Are you running latest master version or not ? This change isnt yet published.

**Comment by javydekoning** [comment]
Ah, yes installing like

```sh
          git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
          . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version
```

**Comment by majkinetor** [comment]
Mhm... not sure why, I run 7.0.3 also without a problem. U say updateall brings this, but this is in individual updaters, does all packages fail or something else happen ?

Did you try to modify the line in original posters question to make it work ?

**Comment by javydekoning** [comment]
Because my `$Env:au_version` was $null `Install-AU.ps1` defaulted to the latest release.

Using setting `$Env:au_version` to `master` fixes the issue indeed.

I didn't realize #216 was not in the latest release.

**Comment by majkinetor** [comment]
No problem :)

**Comment by javydekoning** [comment]
I still face the issue because of: https://github.com/majkinetor/au/blob/e8f8337a5bf4d30bf02c1c636cc86c7d1949682b/AU/Plugins/Gist.ps1#L49

And: 
https://github.com/majkinetor/au/blob/b976947bbf473444912acaf95512846c0ee2d66a/publish.ps1#L58

```
Running Gist
  ERROR:  
    Exception setting "SecurityProtocol": "The requested security protocol is not supported."
```

**Comment by majkinetor** [comment]
Thx for reporting this. `publish.ps1` isn't used by AU but myself when publishing new version.
