### ISSUE TITLE
Update-Package Unknown file type

### ISSUE THREAD

**Issue by jonasw234** [majkinetor/au#207]
I’m trying to create an au package for the [0patch agent](https://0patch.com/index.html). When I use PowerShell to download the latest release using `Invoke-WebRequest -Uri https://dist.0patch.com/download/latestagent -UseBasicParsing` it works as intended and I receive the file with the filename in the response headers:
```
RawContent        : [...]
                    Content-Disposition: attachment; filename=0PatchInstaller_19.11.15.10650.msi
```
However when I use `Update-Package` to let au update an old version of the package, it seems like the filename is not read from the headers but from the URL so it fails with the “Unknown file type” exception.
Is there a way to make au read the filename from the headers instead of from the URL?

**Comment by majkinetor** [comment]
Not currently. You should disable those checks and do them yourself the way you want it.

**Comment by jonasw234** [comment]
Ok, thanks, I’ll try that!
