### ISSUE TITLE
Update version in dependencies for meta packages

### ISSUE THREAD

**Issue by JonasGroeger** [majkinetor/au#22]
Currently, for example for the 7zip package: the `package/metadata/version` xpath gets updated. `package/metadata/version/dependencies/.../id=$packagename` does not.

This is useful for metapackages. It happens here: https://github.com/majkinetor/au/blob/master/Update-Package.ps1#L229

Reference: https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#what-is-the-difference-between-packages-named-install-ie-autohotkeyinstall-portable-ie-autohotkeyportable-and--ie-autohotkey
I would:

    * Iterate through the dependencies (if any)
    * See if I have a dependency to `/package/metadata/id/` `.install` / `.portable`
    * If yes, update its version parameter to version=[$version]. The brackets are for exact match.

Edit: I coded something

```
$latest_version = "5.3.0" # Don't put that in. It already is.

$maybeDependencies = @(
    ($nu.package.metadata.id + '.portable'),
    ($nu.package.metadata.id + '.install')
    
)
$nu.package.metadata.dependencies | ForEach-Object {
    if($maybeDependencies -contains $_.dependency.id)  {
        # We have a dependency to a package with the same name + (.install/.portable)
        # Thus, we are probably a meta package and need to update the version aswell
        $_.dependency.SetAttribute("version", "[" + $latest_version + "]")
    }
}
```

Put the code between line 229/230 and it should work as expected.

**Comment by majkinetor** [comment]
The search and replace system allows you to replace anything in any file, including nuspec file. The metapackage scenario could benefit from it. You just need to craft regex that replaces the tag value.

@ferventcoder, what do you think ?

**Comment by ferventcoder** [comment]
@majkinetor 👍  yes, I believe this is the case.

**Comment by majkinetor** [comment]
While creating a sample for you, I constructed an awesome method for the metapackages to reuse AU updaters from the dependencies with the current AU features.

Take a look at my [cpu-z](https://github.com/majkinetor/chocolatey/blob/master/cpu-z/update.ps1) package that depends on [cpu-z.install](https://github.com/majkinetor/chocolatey/blob/master/cpu-z.install/update.ps1).

This is the output ( I manually changed nuspec version to lower to trigger the update as `Force` is buggy and keeps inserting remote version):

```
PS C:\Work\chocolatey\cpu-z> $au_NoCheckChocoVersion = $true; .\update.ps1
cpu-z - checking updates
nuspec version: 1.76
remote version: 1.77
New version is available
Updating files
  cpu-z.nuspec
    updating version:  1.76 -> 1.77
  cpu-z.nuspec
    (\<dependency .+?"cpu-z.install" version=)"([^"]+)" = $1"1.77"
Chocolatey v0.10.0
Attempting to build package from 'cpu-z.nuspec'.
Successfully created package 'C:\Work\chocolatey\cpu-z\cpu-z.1.77.nupkg'
Package updated
```

**Comment by JonasGroeger** [comment]
@majkinetor Is there a reason you used regex instead of parsing the xml?

    [xml]$nuspec = Get-Content <xml-file>

**Comment by majkinetor** [comment]
Did you RTFM ? :)

No, `au_SearchReplace` doesn't return an array. It returns a HashTable wich contins sesarch keywords as keys and replace keywords as a value..  hence its name.

`$Latest.PackageName` contains the name of your package, its injected by the AU. You don't have to use it, this way the line is generic and works with any package.

The stuff before `=` is just normal reg ex. The stuff after is just normal replace .

With `key = value` what AU does is `(gc <file>) -replace key, value`. This is how you determine the string yourself. You open PowerShell, `gc file` and massage the key in above command until you get the desired result. 

Thats why I didn't use the XML commands, they are not generic enough. S&R works with any text file.

**Comment by JonasGroeger** [comment]
I'm kinda new to powershell so forgive me, master :) Thanks for the explanation!

**Comment by majkinetor** [comment]
No problem @JonasGroeger.
