### ISSUE TITLE
Workflow for Wiki changes

### ISSUE THREAD

**Issue by jberezanski** [majkinetor/au#223]
The [AppVeyor page](https://github.com/majkinetor/au/wiki/AppVeyor) could use a few corrections and updates. As far as I am aware, GitHub does not offer any facility for proposing/reviewing Wiki changes. 

What is the customary workflow in this repo? Should I just make the edits, since the Wiki is publicly writable?

**Comment by majkinetor** [comment]
Just go for it, its publicly writeable by design :)
