### ISSUE TITLE
Historic report is no longer shown

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#231]
For some reason historic report (clicking on first letter in Report History) always redirects to latest report instead of particular revision. Not sure why...

/cc @AdmiringWorm @Thilas

**Comment by majkinetor** [comment]
I noticed bot commit no longer contains revision. This is where it happened:

2020-10-11 between 06-12h
![image](https://user-images.githubusercontent.com/85767/99973207-ce5a3380-2d9f-11eb-8433-0eff6633a6dd.png)

This happened after gist plugin is updated in 8h by @matthewprenger:

![image](https://user-images.githubusercontent.com/85767/99973439-0eb9b180-2da0-11eb-90fc-fd99aeed93df.png)

@matthewprenger can you check it out, I have to revert this commit otherwise.

**Comment by matthewprenger** [comment]
Logged #232 which should fix this.
