### ISSUE TITLE
Git plugin: adding new packages

### ISSUE THREAD

**Issue by jberezanski** [majkinetor/au#239]
The update machinery for [.NET packages](https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages) is set up in such a way that when Microsoft releases a new SDK "feature band" (.1xx, .2xx etc.) a new package is automatically generated from a template. Unfortunately, the Git plugin only adds modified files. As a consequence, the new package is generated, packed and pushed to chocolatey.org, but not committed to the repo, requiring manual syncing up later.

Would you accept a PR with a switch for the Git plugin enabling adding of new files?

**Comment by majkinetor** [comment]
Why not. Go for it.
