### ISSUE TITLE
64 bit only packages

### ISSUE THREAD

**Issue by jamesmyatt** [majkinetor/au#242]
I'm trying to make a package for an application that is 64-bit only on Windows (https://github.com/conda-forge/miniforge).
How should this be handled? When I return no `URL32` from `au_GetLatest`, it says "This package does not support 64 bit architecture." and replaces the checksum64 parameter with `''`.

**Comment by AdmiringWorm** [comment]
Sounds like you are relying on au's built-in automatic checksums, if that is so you need to change the line saying `update` (or `Update-Package`) to only check for the 64bit edition, ie change it to `update -ChecksumFor 64`.
Here is an example: https://github.com/AdmiringWorm/chocolatey-packages/blob/master/automatic/authy-desktop/update.ps1#L30

**Comment by jamesmyatt** [comment]
@AdmiringWorm Thanks. I'll try that.

**Comment by jamesmyatt** [comment]
Seems to work. Thanks
