### ISSUE TITLE
Change path to package

### ISSUE THREAD

**Issue by kamack38** [majkinetor/au#251]
Can I change path to where I want to save `.nupkg` files?

 For Example : 
I have `package 1` and `package 2`

```
├───package 1
│   └───tools
├───package 2
│   └───tools
└───nupkgs
```

And I want to save the files to `nupkgs` folder.
How can I do that?

**Comment by kamack38** [comment]
```
AfterEach = {
    Get-ChildItem -Depth 1 | Where-Object Name -Match .*.nupkg | Move-Item -Destination .\nupkgs\ -Force
}
```
I've added this to `update_all.ps1`, but how can I add this inti `test_all.ps1`?

**Comment by kamack38** [comment]
I've added hti into `test_all.ps1`
```
$options = [ordered]@{
    AfterEach = {
        Get-ChildItem -Depth 1 | Where-Object Name -Match .*.nupkg | Move-Item -Destination ..\nupkgs\ -Force
    }
}
```
And now it works!
Thank you for your cooperation.

**Comment by majkinetor** [comment]
No problem :)
