### ISSUE TITLE
PostgreSQL packages failing to upload

### ISSUE THREAD

**Issue by dvarrazzo** [majkinetor/au#252]
PostgreSQL packages 14.1, 13.5, 12.9, 11.14, 10.19, and 9.6.24 [have been released](https://www.postgresql.org/about/news/postgresql-141-135-129-1114-1019-and-9624-released-2349/). They contain a fix for a few security issues.

Apparently the packages have been built but uploading on Chocolatey fails. [Error report is here](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#ignored).

Waiting for the solution to release upgrade psycopg packages: https://github.com/psycopg/psycopg/issues/149

Thank you very much

**Comment by majkinetor** [comment]
Invalid repository and duplicate ticket:

- https://github.com/majkinetor/au-packages/issues/201
