### ISSUE TITLE
How to avoid adding date revision number to the packageName and nuspec file  in force update

### ISSUE THREAD

**Issue by moh-hassan** [majkinetor/au#253]
When run the [demo](https://github.com/majkinetor/au-packages-template/tree/master/copyq) with the command
```
 $au_Force = $true; .\update.ps1
```
if  nuspec version match the remote version, i.e 5.0.0,  au use date as a revision number and attach it to  Version and generate package like: `copyq.5.0.0.20211117.nupkg`

and nuspec version is modified to: ` <version>5.0.0.20211117</version>`
 
 How to avoid adding date revision number in force update?

**Comment by majkinetor** [comment]
Use `$au_Version`.

**Comment by moh-hassan** [comment]
Thanks for reply.
How to use `$au_Version`.

**Comment by majkinetor** [comment]
`$au_Force = $true; $au_version = "5.0.0"; .\update.ps1`

**Comment by moh-hassan** [comment]
I didn't want to pass a fixed value. I want to use the `$au_version` by dropping the revision number. Is the above script the best use for dropping the revision number?

**Comment by majkinetor** [comment]
OK, set version in nuspec file to 0.0 programatically before calling update. Then it will never be fixed.

**Comment by moh-hassan** [comment]
It works.
It's fine if there is a parameter  `-DropRevision` to use only  x.y.z version (SemVer)
