### ISSUE TITLE
Report plugin has hard coded links

### ISSUE THREAD

**Issue by danmetzler** [majkinetor/au#257]
This issue is similar to #244, but a little more broad than just a hard coded "branch".  In my scenario, I would like to use AU to automate updates for a private repository.

* I'm attempting to get things working on a repository that is hosted on a Gitlab server, so the link generated for the Update_all script is broken.  (Could be handled with a variable.)
* Also the links to packages assume `https://chocolatey.org` in the markdown table, so doesn't work for a private internal repo whose packages may not always have corresponding packages on Chocolatey.org.  (The `$au_GalleryPackageRootUrl` variable could probably be used to address this.)

Does it make sense to fix this in the report plugin that comes with AU?  Or do people normally write all custom plugins for a scenario like this?

(I would be happy to work on a pull request, if it makes sense to address this in the built-in AU plugin.)

**Comment by majkinetor** [comment]
Sure, go for it. Add variables to the plugin with default values .
