### ISSUE TITLE
History plugin not parsing date correctly

### ISSUE THREAD

**Issue by danmetzler** [majkinetor/au#258]
I'm using Git version 2.34.1, and seem to be getting errors in the History plugin.

Appears the issue is [here](https://github.com/majkinetor/au/blob/master/AU/Plugins/History.ps1#:~:text=%24date%20%20%20%20%20%3D%20%24commit%5B2%5D.Replace(%27Date%3A%27%2C%27%27).Trim()). (line 35)

For me the date is at index 3 instead of index 2.

Since my setup is new, I'm not sure if this is an issue specific to my git config, or more tied to the version of Git, or something that is more widely experienced.  (I think it has never worked for me, but maybe others have different experience?)

**Comment by danmetzler** [comment]
One way to check if the issue exists on a system:

```powershell
$log = git --no-pager log -q --grep '^AU: ' --date iso --all | out-string
$all_commits = $log | Select-String 'commit(.|\n)+?(?=\ncommit )' -AllMatches
$commit = $all_commits.matches[0]
$commit = $commit -split '\n'
$date     = $commit[2].Replace('Date:','').Trim()
$date     = ([datetime]$date).Date.ToString("yyyy-MM-dd")
```

If the last command fails, the issue is there.

**Comment by danmetzler** [comment]
On further investigation this happens with a merge commit.  In that scenario, the next line after the commit line is of the format ```Merge: <ref> <ref>```.  Then author and date are shifted down one to the 3rd and 4th lines.

**Comment by majkinetor** [comment]
Ah, that must be it, we don't have merges with described AppVeyor system so that setup was never taken into consideration.

**Comment by danmetzler** [comment]
It seems to me there are a couple of approaches we could take to fix:

* We could assume that this is a really rare thing, (I think that's true), and allow the History plugin to generate a bad entry for that commit.  Maybe the date shows "(could not be parsed)", and the packages are are something similar.  (This just keeps it from erroring.)  Or,
* We could assume that this merge commit is the problem where this would occur, but try to make the History plugin "do the right thing", and handle the merge commit appropriately.  (I think the right thing is probably ignore merge commits, even if they contain an "^AU" line in them.)

If we want to do the second option, I think we could look at the commit line that normally contains "Date:" and if it doesn't contain "Date:" then assume it is a merge commit and don't include it.

Any thoughts?

**Comment by majkinetor** [comment]
Lets just add `--no-merges` param to `git log` and call it a day.

**Comment by danmetzler** [comment]
> Lets just add `--no-merges` param to `git log` and call it a day.

Perfect!
