### ISSUE TITLE
Where I can add headers when downloading file ?

### ISSUE THREAD

**Issue by Starmania** [majkinetor/au#263]
Hey, 
I'm curently triing to download a release to calculate his SHA, but the file when downloading, need some headers... 

I don't know why but if I do by Invoke-WebRequest in my terminal, all is fine, but if I do by AU, I reach a 403 err...

**Comment by majkinetor** [comment]
You can use `$Latest.Options.Headers`

**Comment by Starmania** [comment]
This is a variable that I set before the `update` command ?

**Comment by majkinetor** [comment]
You set it in `Get-Latest`.
