### ISSUE TITLE
Update 2016.8.15 --> 2016.9.14.233253 does not show PackageName correctly

### ISSUE THREAD

**Issue by JonasGroeger** [majkinetor/au#27]
See the diff @ https://gist.github.com/JonasGroeger/1f744e419f66de0f36511222bfa1d204/revisions?short_path=02b5cdb#diff-02b5cdbd2c4adb9b30540fb83f04bb86

**Comment by majkinetor** [comment]
That is already fixed, its just not yet released. Will do it in next couple of days when I finish some few other things.

**Comment by JonasGroeger** [comment]
That was fast. Thanks!
