### ISSUE TITLE
NuSpec file not found if name of the .nuspec file is not equal to the name of the folder

### ISSUE THREAD

**Issue by pascalberger** [majkinetor/au#49]
The following error is thrown if the name of the NuSpec file contains a dot (eg. git-lfs.install.nuspec):

```
No nuspec file found in the current directory
At C:\Program Files\WindowsPowerShell\Modules\AU\2016.11.5\Public\Update-Package.ps1:326 char:25
```

**Comment by majkinetor** [comment]
Thats strange, I have packages with dot.

**Comment by majkinetor** [comment]
Anyway, would you care to try with the latest artifact (see install section, 7z archive). It has some changes related to this.

**Comment by pascalberger** [comment]
Latest artifact didn't help. I anyway was already at 2016.11.5.

OS is Windows 10. PowerShell version 5.1.14931.1000.

**Comment by pascalberger** [comment]
Sorry, I just found out that the dot is not the issue, but instead if the .nuspec is named differently than the name of the folder which contains the .nuspec.

**Comment by majkinetor** [comment]
Yeah, it just crossed my mind. That is not supported.
