### ISSUE TITLE
Changes not commited if upload runs into timeout

### ISSUE THREAD

**Issue by pascalberger** [majkinetor/au#51]
I had a case where pushing the package to Chocolatey ran into a timeout (https://ci.appveyor.com/project/pascalberger/chocolatey-packages/build/52), but even though was pushed to Chocolatey. AU afterwards didn't commit the changes, which makes sense since the push indicated an error. Maybe increasing the timeout for the request in AU would help to improve this situation.

**Comment by majkinetor** [comment]
Timeout can br configured in Options.
Also,  besides package source not being uptodate everything should still work.
