### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by teknowledgist** [majkinetor/au#52]
I'm trying to figure this out because, hey, automation is cool.  I get the basic idea, but I'm not sure how to proceed because the documentation on this is a bit scattered.  

For example: [This](https://chocolatey.org/docs/automatic-packages) says PowerShell v4 (soon to be PoSh v3) is required, while [this](https://github.com/chocolatey/chocolatey-packages-template) says PoSh v4, and [this](https://github.com/majkinetor/au/blob/master/README.md) says PoSh v5.  All the while, the [package itself](https://chocolatey.org/packages/au) has no dependencies.  

I suspect a lot more maintainers would be willing to jump in the AU pool if there was some step-by-step instructions.  As it is, there is information on functions and some examples, but it is up to the reader to absorb all of it and piece it together.  I have created packages because I need to make things more automated, not because it's easy.  Making them automated is a meta-level above creating the packages, and having a simple walk-through that I can do (not a "look at this existing package and be enlightened") would really help me get started.

Thanks for making this even possible for mere mortals!

**Comment by majkinetor** [comment]
Hey there

Documentation is not a bit scattered - there is only one: README.md (and wiki too contains details). What happens on other places is irrelevant.

Now, let me clarify this for you:
- Powershell version for **current release** is 4.
- for NEXT release (not yet published) is 5. What is asap shown on github is readme for the next release, to get the previous one go to specific release.

Other sites are irrelevant, including chocolatey related. 

> I suspect a lot more maintainers would be willing to jump in the AU pool if there was some step-by-step instructions. 

There is a step by step [video](https://www.youtube.com/watch?v=m2XpV2LxyEI&feature=youtu.be) tutorial.

>  I have created packages because I need to make things more automated, not because it's easy.

I like that attitude 💯 

Anyway, the best place to ask for help is au gitter chanel.
