### ISSUE TITLE
New checksum method

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#54]
Sometimes `ChecksumFor` is problematic as it invokes choco installer. 

We now have `Get-RemoteChecksum` that you can call inside `au_GetLatest` but it will download the file even if its not needed so you would have to protect from that with something like:

    if ($Latest.NuspecVersion -lt $version) { $Latest.Checksum32 = Get-RemoteChecksum $url}

But it cant be that simple as versions are not [version] or [semanticversion] and require custom comparison function.

So we have 2 options:

- Implement `IsUpdated` that can be used in `au_GetLatest`:  `if (IsUpdated) { $url32/64 = GetRemote-CHecksum $url32/64 }`
- Provide `ChecksumMethod` parameter: `update ... -ChecksumMethod internal`  
The method `internal` would use `Get-RemoteChecksum` if there are updates. The default method could stay `choco` to call chocolatey installer as before.

**Comment by majkinetor** [comment]
I personally think that option 2 is better as it will actually do what you have to manually od in option 1 and is consistent with previous behavior (doesn't surprise).

I wonde is there any convenient argument to have `IsUpdated` function available for other reasons.

**Comment by AdmiringWorm** [comment]
I was thinking a little more on this, isn't it possible to call `Get-RemoteChecksum` in the `au_SearchReplace` function?
Then it would be unnecessary to change this, (and unnecessary to add a new function as I tried to suggest)

**Comment by majkinetor** [comment]
You are tootally right :) Didn't thought about this. Perhaps we can try it on few packages and see how it behaves.

**Comment by majkinetor** [comment]
As a semi related note, the `Get-RemoteChecksum` is very handy when updating manual packages with checksums.

**Comment by AdmiringWorm** [comment]
> @majkinetor 
> You are tootally right :) Didn't thought about this. Perhaps we can try it on few packages and see how it behaves.

I'm testing it out on the flighgear package right now.

**Comment by AdmiringWorm** [comment]
I just finished testing the flightgear package with the following changes:
https://github.com/AdmiringWorm/chocolatey-coreteampackages/commit/5c04acefb395eadea92937c400bd1f4994fe88a1

running on appveyor with force update:
https://gist.github.com/AdmiringWorm/30a8b66d4c02ecacce2da3c8734ac61f/52415a88c6abdaf3aa8aa675668cd313b35c3299

also tested it locally without forcing the update, and it works as expected (No download and no checksum hashing).

Haven't yet pushed it to the main repo, but will soon...
