### ISSUE TITLE
Support for multiple software versions

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#56]
> Does AU support multiple maintained versions having releases? 

> Like for Virtualbox, 5.0.x continues to release newer versions in tandem with 5.1.x. So you technically need to be detecting both and creating packages for them. In ketarin we set this up as a different job to support checking for older version releases.

**Comment by ferventcoder** [comment]
Ruby, NodeJS, other tools also have this approach of multiple supported versions over time.

**Comment by majkinetor** [comment]
This can be done by setting up a separate AU package like this:

1. Copy the existing package but give to new folder and rename the nuspec file according to the folder name.
1. In `au_GetLatest` set the correct packageName as it will by default be the same as directory name: $Latest.PackageName = <desired_package_name>
