### ISSUE TITLE
Pre-Release updates not detected properly

### ISSUE THREAD

**Issue by AdmiringWorm** [majkinetor/au#59]
When a pre-release have already been pushed to chocolatey,
and if during update there is a new pre-release version, au still thinks it exists.

Example with juju package:
https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e#juju

Version: 2.1-beta1 exists on chocolatey (and in the nuspec),
Version: 2.1-beta2 is the new version upstream, but au thinks it is the same version.

**Comment by majkinetor** [comment]
Should work now.

**Comment by AdmiringWorm** [comment]
👍
great, just tested it locally and it updates now.
