### ISSUE TITLE
Set additional properties in Get-RemoteFiles

### ISSUE THREAD

**Issue by AdmiringWorm** [majkinetor/au#64]
Currently `Get-RemoteFiles` feels a little unusable as you don't know what filenames it is resolved to, unless you replicate the file name behaviour yourself.

It would be great if it also sets the resolved filename and checksumtypes (also allowing to override which algorithm to use)

i.e.
settings `FileName32` and `FileName64`.
And also `ChecksumType32` and `ChecksumType64`

**Comment by majkinetor** [comment]
> Currently Get-RemoteFiles feels a little unusable

Thats probably because your programming style is different then mine. I used it on 15 or so packages and I never really needed to know the file name, I used wildcards in installer. 

I always wondered why you guys make it harder then it is required... Almost all of my packages have the very same part of the installer - I usually only change the silentArgs. This makes both installer and update.ps1 simpler and less errorprone.

**Comment by majkinetor** [comment]
See my template -  https://github.com/majkinetor/au-packages/blob/6e157dc7126b91a3293f2417a583be47bcefc5d1/_template/tools/chocolateyInstallEmbededExe.ps1

**Comment by AdmiringWorm** [comment]
> I used wildcards in installer

and that's something I don't like to do when it's not needed.

> I don't really see a reason of keeping the original file name intact comparing to the benefit I get with arch suffix

let me give you a hypothetical probability.
I know you removes the installer after it has been used, but lets say that removal fails (maybe a lock wasn't released in time or something) and the package is installed.
Now when a package is updated and the user then tries to upgrade the package, now the package will contain two installers that will match the wildcard, which one will be used?
Most likely it will pass both installers to the `Install-ChocolateyInstallPackage` function which will then make the upgrade fail.
If it won't give both installers, then it will be using the first matching installer (by ascending order) which will just try to install using the old installer, which again is wrong.

**Comment by majkinetor** [comment]
> and that's something I don't like to do when it's not needed.

 It might not be theoretically right thing to do in general context, but if you can't show me the problem with it, then you are not being rational. And please no 'hypothetical probability'. Give me concrete example where it went wrong and I will be happy to admit I suck.

> Now when a package is updated and the user then tries to upgrade the package, now the package will contain two installers that will match the wildcard, which one will be used?

This is indeed possible scenario which never happened for me and is easily solvable with few more chars: gi * | sort -property CreationDate | select -first 1. 

Also, I think choco now cleans up the folder before install AFAIK ? (might be wrong, I based this on observation).

**Comment by majkinetor** [comment]
But to be honest, its probably a good idea to have that - if nothing else, it might be useful when lookin at the logs.

Feel free to PR it based on your needs and I will merge it.

**Comment by AdmiringWorm** [comment]
@majkinetor I'm about to prepare to leave for work,
but I'll open a PR when I get home.

Would you mind if I also added a parameter for allowing users to override the algorithm used for generating checksums?

**Comment by majkinetor** [comment]
No problem. I support options as long as they have sane defaults.
