### ISSUE TITLE
Error when installing: Package does not support 64 bit architecture

### ISSUE THREAD

**Issue by bspeice** [majkinetor/au#70]
I'm getting the following error message when trying to create a new package. The chocolateyinstaller.ps1 script is built using the standard template from Chocolatey, so I'm not sure why I'm getting such a message - the 64-bit URL is specified in both `update.ps1` and `chocolateyinstall.ps1`.

```
PS C:\Users\bspeice\Development\au-packages\reaper> .\update.ps1
reaper - checking updates using AU version 2017.1.14
URL check
  http://reaper.fm/files/5.x/reaper535_x64-install.exe
  http://reaper.fm/files/5.x/reaper535-install.exe
nuspec version: 5.34
remote version: 5.35
New version is available
Automatic checksum started
This package does not support 64 bit architecture.
At C:\Users\bspeice\AppData\Local\Temp\chocolatey\au\chocolatey\helpers\functions\Get-ChocolateyWebFile.ps1:257 char:5
+     throw "This package does not support $bitWidth bit architecture."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (This package do...t architecture.:String) [], RuntimeException
    + FullyQualifiedErrorId : This package does not support 64 bit architecture.
```

My recent code can be found at: https://github.com/bspeice/au-packages/tree/30743919a9255c9fc36554d292b23348a4760723

**Comment by majkinetor** [comment]
You have a [typo](https://github.com/bspeice/au-packages/blob/30743919a9255c9fc36554d292b23348a4760723/reaper/tools/chocolateyinstall.ps1#L14
) in your chocolateyInstall.

This is a typical error when that happens. BTW, you can move all variables inside the @params section. Take a look at my packages and/or use my [template](https://github.com/majkinetor/au-packages/blob/master/_template).

**Comment by bspeice** [comment]
Sure enough, fixed right up. Thanks for the assistance!
