### ISSUE TITLE
Method to follow updates to multiple version streams

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#74]
I.E virtualbox, ruby etc... 

Currently you must create separate package for each. This is clearly bad for so many reasons, discover-ability and non-intuitiveness to be major ones. 

With this, the one can later follow updates of specific stream like this:

```powershell
function cinst-stream( $pkg, $ver) {
    $latest = (choco list -ea $pkg | sls "$ver.+" | select -First 1) -split ' ' | ? { try {[version]::Parse($_)}catch{}  }
    Write-host $pkg $latest
    
    choco pin remove -n=$pkg
    cinst $pkg --version $latest
    choco pin add -n=$pkg
}

cinst-stream ruby 1.9

```

This would install `ruby 1.9.2.291` and will get updated to latest 1.9 stream when it appears on gallery. Pin would prevent `cup all` to update package to highest version available.

**Comment by majkinetor** [comment]
Something like this:
```
au_GetLatest() {

       $streams = @{
            $status = gc streams            # stream2.2 = '2.2.3'
                                            # stream2.3 = '2.3.9.1'

            $stream2.2 = {
                url = $download-page.links -href
                @{
                    $url32 = ...
                    $url64 = ....
                    $version = ...
                }
            }
            
            $stream2.3 = {
                url = $download-page.links -href
                @{ 
                    $url32 = ...
                    $url64 = ....
                    $version = ...
                }
            }
       }

       # normal au_GetLatest

       if (!is_updated) { $streams.Keys | ? $streams[$_] -is [scriptblock] | % { 
            $ls = . $streams[$_]      # get latest from streasm
            if (is_updated $ls.version $streams.$_=) { 
                $global:au_force = $true;  $global:au_version = $sl.version
                return $sl 
            }
     }
}
```

- `is_updated` could be (really should) be exposed AU internal function.
- file `streams` kaeps latest stream versions.

**Comment by AdmiringWorm** [comment]
I like the idea.
But there could perhaps be another option to consider:
Allowing multiple functions that starts with `au_GetLatest*` instead of using streams (I don't know if this is possible though, but it probably is).
The benefit of that IMO would then be to have the necessary code to use contained in a their own function, instead of having it all packed inside just the `au_GetLatest` function.

**Comment by majkinetor** [comment]
I like that.

**Comment by majkinetor** [comment]
> Allowing multiple functions that starts with au_GetLatest* instead of using streams (I don't know if this is possible though, but it probably is).

On the second thought, this method would be much harder to allow for automatic stream getting via a page on vendor site that list streams in maintenance. Don't know if anybody would automate this tho...

**Comment by Thilas** [comment]
I was thinking about this and I guess both cases could be interesting. But in my experience, I think the case where `au_GetLatest` returns all streams is the best way to do it for the exact reason mentioned by @majkinetor.

And since I'm interested in having such streams support, I created PR #98 to propose something. Let me know what you think about it.

**Comment by majkinetor** [comment]
@Thilas 

One package failed on my repo with streams:

https://github.com/majkinetor/au-packages/blob/ff1f1eea3a09a2ceef02c0e2590031c655c8dff1/trid/update.ps1#L34

https://ci.appveyor.com/project/majkinetor/au-packages/build/887#L146:
```
 trid ERROR: 
     au_GetLatest failed 
     The property 'checksum_trid' cannot be found on this object. Verify that the property exists and can be set
```

**Comment by Thilas** [comment]
@majkinetor, fixed in PR #100.

**Comment by majkinetor** [comment]
@Thilas, would you mind joining https://gitter.im/chocolatey/chocolatey-coreteampackages ? 

We are going to try streams there.

**Comment by Thilas** [comment]
Sure!

**Comment by majkinetor** [comment]
@Thilas , would you mind checking this PR:
https://github.com/chocolatey/chocolatey-coreteampackages/pull/887#pullrequestreview-72963349

**Comment by Thilas** [comment]
Looks good to me. No remarks on my side.

**Comment by Thilas** [comment]
@majkinetor, @AdmiringWorm, @gep13, @ferventcoder, given the current implementation for streams and the recent experiment to use them in coreteampackages, do you have any suggestions to make it more suitable? Or do you think it is ok as is?

Here are the different ideas from previous discussions:

- [ ] Allow to set common stuff for all streams at the root of the `au_GetLatest` return value:
```powershell
   au_GetLatest() {
       $download_page = iwr ....
       ...
       #normal get latest here
       $result = @{ SilentArgs = '/s1' ... }

       # calculate stream's Latest's
       $url = $download_page.links.href -match '1.9.+zip'....
       $result.streams.'1.9' = @{
              Url32 = ...
              Version = ...
        }

       $url = $download_page.links.href -match '2.3.+zip'....
       $result.streams.'2.3' = @{ 
              Url32 = ...
              Version = ...
        }
 
       return $result
}
```
That way, for each stream, the global variable `$Latest` would be initialized with common stuff as well as stream specific stuff before calling `au_SearchReplace` & other public AU functions:
```powershell
       $Latest = @{
              Url32 = ...
              Version = ...
              SilentArgs = '/s1'
              ...
       }
```
- [ ] Allow to implement streams using `au_GetLatest*` functions, though I don't think of cases where it would benefit this way compared to what can be done now.
- [ ] Allow people to PR any new versions (see chocolatey/chocolatey-coreteampackages#812).

**Comment by AdmiringWorm** [comment]
A few suggestions that I can think of.

1. In the streams key, allow pretty much any arbitrary string to be passed as the key.
    Don't enforce them to comply with being a valid version.
    For instance, in a package where we want to support both stable and unstable releases, but we don't really care about the version of them, until it have been updated.
    Make it available to label them as `stable`, `unstable`, `beta` or whatever we want (man running from dog).
2. instead of only accepting hashtables int the value of a stream, also allow passing in a scriptblock which is then run by AU when the stream is needed (haven't really tested, but I don't think this scenario is supported right now).
3. Store a little more information about the streams, and pass that along to the Plugins.
    Pretty much storing the same information as when a stream isn't used, just doing that per stream instead.

A like the idea of setting common stuff for all streams.

**Comment by Thilas** [comment]
> 1. In the streams key, allow pretty much any arbitrary string to be passed as the key.

I thought too about allowing any strings to identify streams (for libreoffice package for instance).
> 2. instead of only accepting hashtables int the value of a stream, also allow passing in a scriptblock

I don't quite understand the purpose of this. Do you have an use case in mind?
> 3. Store a little more information about the stream

Could you elaborate a bit? What kind of information? To do what?

**Comment by AdmiringWorm** [comment]
> I don't quite understand the purpose of this. Do you have an use case in mind?

Well, you can think of it like a kind of lazy-loading in cases where you need to hit multiple locations to determine the information for each version.
So in cases where you, say only want to force a fix version of a certain version, you wouldn't want to have to hit every location when it isn't necessary, but only those locations that are needed to actually update that exact version (which can be done by accepting scriptblocks, I think)

> Could you elaborate a bit? What kind of information? To do what?

For instance, the same information that is stored on non-streams (PackageName, NuspecVersion, RemoteVersion, etc). In the plugin I PR'd previously before I was aware of the streams, I used those to determine the information to create different releases, with the inclusion of streams that information wasn't available anymore for all streams, just for the latest.
Having that information included in the $Info object for streams could be helpful, especially in cases where the PackageName have been changed in that specific stream.

**Comment by Thilas** [comment]
Thanks for the examples, it's clearer to me now.

IMHO, lazy-loading of versions will not be that useful, it's mostly a matter of saving time while updating. So I wouldn't focus on it right now.

About the 2nd point, if I understand well, you would like basically to access the return value of the `au_GetLatest` method, right?

**Comment by AdmiringWorm** [comment]
> IMHO, lazy-loading of versions will not be that useful, it's mostly a matter of saving time while updating. So I wouldn't focus on it right now.

true, it won't be a huge benefit. But still something that should be considered, even at a later date IMO.
The benefit will only show themselves when needing to update a single stream though, especially in cases where quite a few of them exists. But agreed, it isn't a priority right now.

> About the 2nd point, if I understand well, you would like basically to access the return value of the au_GetLatest method, right?

Well yes and no, while some of the parameters I mentioned are available there, not all of them are (the NuspecVersion isn't, the PackageName may also be set later)

**Comment by Thilas** [comment]
Sure, it would be the return value + properties added by AU, right?

**Comment by Thilas** [comment]
I've worked on a few things discussed here this week-end:
- changes on AU streams: https://github.com/majkinetor/au/pull/109
- use alphabetical streams on libreoffice: https://github.com/chocolatey/chocolatey-coreteampackages/pull/892

I still need to test one more thing on AU's PR on my own repo and then it's good to go for me (by tonight).

Let me know what you think. Thanks.

**Comment by Thilas** [comment]
PR #109 is merged now:
- Support alphabetical streams (not version-like streams)
- Add support for common properties shared between all streams
- Add more information on streams for plugins (+ adapt GitReleases)
- Rename Include argument into IncludeStream on Update-Package
- Add more pester tests (+ enable code coverage)

Anything else or can we close this issue?
