### ISSUE TITLE
524 error from pushing package to Chocolatey prevents code changes to be committed

### ISSUE THREAD

**Issue by flcdrg** [majkinetor/au#75]
So I was looking forward to seeing my first package automatically updated without me watching it this morning.. but it [had a little hiccup](https://ci.appveyor.com/project/DavidGardiner/au-packages/build/16) when it got to pushing the new package version to Chocolatey.org

> Failed to process request. 'Origin Time-out'.  The remote server returned an error: (524) Origin Time-out..

I've seen this occasionally when manually pushing a package - the error is returned even though the package [did actually get pushed](https://chocolatey.org/packages/ubiquiti-unifi-controller/5.4.15). It's also been seen by others - https://github.com/chocolatey/chocolatey.org/issues/499

But I presume because AU thinks that something went wrong, it then doesn't commit the code changes back to my repo, and re-running the build now doesn't help as the next run it sees the newer version is already on Chocolatey so it has nothing to do.

So I'm wondering whether AU should look for this error code and maybe do a sanity check to see if the package did actually get uploaded, and if so then not fail

**Comment by majkinetor** [comment]
I was thinking about doing that but finally concluded that it has to happen upstream because it is valid behavior for people to push existing package fixes which go to the same version so no sanity check is possible in which case that push error  wont be seen.

Since this is given high priority I suspect it will be fixed soon enough. Important thing is that package get pushed, the fact that source code isn't 100% latest is a minor point (the package wont show in report history too).

**Comment by flcdrg** [comment]
Just to be clear - that 524 error is not because I was pushing the same package version - it's because CloudFlare is being weird in front of Chocolatey.org.

**Comment by majkinetor** [comment]
Yeah, I know, but it happens on same version too, using `[AU pkg:existing_version]` command.

**Comment by flcdrg** [comment]
Sure, given that it's a CloudFlare thing I'd expect it could show up in various places.

So it is legal to push the same version of a package, as long as that version hasn't been approved. In both cases if you got this error, then could you not do a query against chocolatey.org to confirm whether the version is there, and for the same version scenario maybe there's an updated time field you could check?

**Comment by majkinetor** [comment]
> and for the same version scenario maybe there's an updated time field you could check

Only date field. Not a time field. :)

I will consider adding this if it doesn't get fixed soon enough (lets give it a month or so).

**Comment by flcdrg** [comment]
Did some poking around and I can see an 'updated' field if you query via something like http://chocolatey.org/api/v2/FindPackagesById()?id=%27ubiquiti-unifi-controller%27

Is that the API you were referring to, or is it something different?

**Comment by majkinetor** [comment]
Thats it. Thanks for the effort.

**Comment by majkinetor** [comment]
There is also new event upstream, might render entire stuff obsolete:

> Folks - use https://package.chocolatey.org to push. I am going to update documentation for this now and adjust it to work as the default for Chocolatey v0.10.6+.

**Comment by majkinetor** [comment]
I changed push source in AU to see how this works: https://github.com/majkinetor/au/commit/46bf476a9a06645eea15c20c75b637cb349e4bed

**Comment by majkinetor** [comment]
To see how that works you must set [AU version to master](https://github.com/flcdrg/au-packages/blob/master/.appveyor.yml#L16) (see [coreteam setup](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/.appveyor.yml#L18))

**Comment by majkinetor** [comment]
Seems that push errors do not appear any more with new URI.
