### ISSUE TITLE
Invalid version error

### ISSUE THREAD

**Issue by Spunkie** [majkinetor/au#77]
I'm getting an invalid version error on what I believe should be a valid prerelease version# of `2017.2-EAP`. I previously encountered a similar error where I needed to pad on an extra `.0` onto the version before AU would accept it but in this case I'm trying to match the non-prerelease version# format so I would prefer not to have to do that.

```powershell
PS C:\GIT\chocolatey-packages\automatic\phpstorm> .\update.ps1
phpstorm - checking updates using au version 2017.3.29
Test version specific releaseNotes url
>>      https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+EAP+172.2103+Release+Notes
Invalid version: PhpStorm 2017.2-EAP
At C:\Program Files\WindowsPowerShell\Modules\au\Public\Update-Package.ps1:324 char:42
+ ... ion $Latest.Version)) { throw "Invalid version: $($Latest.Version)" }
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invalid version: PhpStorm 2017.2-EAP:String) [], RuntimeException
    + FullyQualifiedErrorId : Invalid version: PhpStorm 2017.2-EAP
```

The update I'm trying to run can be found here: https://github.com/Spunkie/chocolatey-packages/tree/master/automatic/phpstorm

**Comment by majkinetor** [comment]
Your version is `PhpStorm 2017.2-EAP`, and PhpStorm is clearly not a valid version :)

**Comment by majkinetor** [comment]
> I previously encountered a similar error where I needed to pad on an extra .0 onto the version before AU would accept it

I am not aware of such thing, please post a concrete version so I can take a look

Version checking is implemented using [`is_version`](https://github.com/majkinetor/au/blob/master/AU/Private/is_version.ps1) function, so you could check it yourself if in doubt.

**Comment by Spunkie** [comment]
omg I'm so blind and dense, even after reading your reply I had to re-read the error output a few more times before I saw it. The actual issue here is the format of the page I'm scraping the version # off of changed format and my regex is subpar. :hankey:

Also I looked up the chat logs about the padding `.0` and my memory is a bit off on what the actual issue was.
> I was initially trying to use the format `2017.1-EAP171378027` or `2017.1.0-EAP171378027` which would work once but then on subsequent runs of `test_all.ps1` it would regenerate itself into `2017.1.0.20170311`. 

I ended up using a format like `2017.1.0.171378027-EAP` which didn't have with issue when running `test_all.ps1` multiple times. This was when I first started using AU so I'll have to retest this and see if it's a real issue or I was just doing something stupid.

**Comment by majkinetor** [comment]
Pre-releases aren't tested with force parameter. I guess it will just remove pre-release. That isn't such a big problem to deserve a special handling or fix IMO especially as fix exists - just use `au_version` explicitly  so AU wont change it in such cases.
