### ISSUE TITLE
Add extension to provide status updates for gitter

### ISSUE THREAD

**Issue by AdmiringWorm** [majkinetor/au#80]
Any thoughts of perhaps allow status updates for gitter?
I'm using one such extension I created myself, but would be nice to see it officially in the AU source.

Example gitter room which shows the status updates of my own packages:
https://gitter.im/wormie-packages/Lobby

and the source of the gitter extension:
https://github.com/AdmiringWorm/chocolatey-packages/blob/master/scripts/au_plugins/Gitter.ps1

Pretty simple, but so far I've not seen any issues with it.

**Comment by majkinetor** [comment]
Not sure how is this valuable on global level with other mechanism in place. 
It can be used by core-team tho and there is probably no harm in submitting it..

OK, why not, provide a PR, update AU wiki on plugins with detailed instructions on how to set it up. I will probably make some trivial changes on PR directly.

**Comment by majkinetor** [comment]
Pending closure
