### ISSUE TITLE
Exception calling `LoadNuspecFile` 

### ISSUE THREAD

**Issue by Nate-Wilkins** [majkinetor/au#81]
I'm getting the following exception. When running `& ./update.ps1` from within the default [`chocolatey-packages-template`](https://github.com/chocolatey/chocolatey-packages-template/tree/master/automatic/html-tidy) repository for `html-tidy`

![image](https://cloud.githubusercontent.com/assets/2957868/26601039/654b0782-454c-11e7-8d4a-a421057c1349.png)

> Exception calling "LoadNuspecFile" with "1" argument(s): "The given key was not present in the dictionary."
> At C:\Program Files\WindowsPowershell\Modules\au\2017.3.29\Private\AuPackage.ps1:22 char:9
>  $this.NuspecXml     = [AUPackage]::LoadNuspecFile( $this.Nusp ...
>   CategoryInfo             : NotSpecified: (:), [], MethodInvocationException
>   FullyQualifiedErrorId : KeyNotFoundException         
> 

I can't seem to figure out where/why this is happening. Nor do I really know how to start digging into the problem.

I'm running on Windows 10 with Powershell version 5.0.10240.17146
I installed the module through chocolatey & through `Install-Module` with the same result. 

Any help is greatly appreciated!

**Comment by majkinetor** [comment]
Can you give the source to the package ?

**Comment by Nate-Wilkins** [comment]
This is the one I want to get working [`ravendb3`](https://github.com/Nate-Wilkins/chocolatey-packages/tree/master/automatic/ravendb3) but I'm running the update command out of the default chocolatey-packages-template repo right now and getting that error also.

**Comment by majkinetor** [comment]
would you mind checking out `au-packages-template` ?

**Comment by Nate-Wilkins** [comment]
I get the same thing running under `copyq`

**Comment by majkinetor** [comment]
Using https://github.com/majkinetor/au-packages-template ?

**Comment by Nate-Wilkins** [comment]
Yeah that's the one I tried debugging into the module and I can't step into that static method at all.

**Comment by majkinetor** [comment]
Feel free to reopen if you find its actually an AU problem which I doubt. You can look into running your stuff on AppVeyor which serves as a reference platform.

**Comment by Nate-Wilkins** [comment]
@majkinetor yeah I started running it on AppVeyor and another machine and it works fine 😂 

Quick question though. Do I need to encode the `url` that I pass to the chocolatey installer? I think that's my last barrier.

**Comment by majkinetor** [comment]
No encoding is necessary generally. I see that raven uses space in URL which is an error on their part, that should be [encoded already](https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space#497972). 

BTW, you don't need to set checksum type and you may consider [embedding](https://github.com/majkinetor/au#embedding-binaries) raven installer into the package so it doesn't depend on vendor site and can be cached (you want this for this type of package, versions are usually important and set on project level). If you want to do so, see `Get-RemoteFiles` and you will have to change the installer.

**Comment by Nate-Wilkins** [comment]
Nice! Yeah I'll do that. 
I'll look into the `Get-RemoteFiles` the main reason this is `ravendb3` instead of just `ravendb` is that it's already taken and hasn't been updated since 2013

I don't know what kindof process I'd have to go through to take ownership but I'd be willing to do that. (Also don't think this is the right forum for this buuttt)
I've reached out through the site but sebnilsson hasn't gotten back to me :(

**Comment by ferventcoder** [comment]
@Nate-Wilkins wrong forum ;) - go to the package page and follow up by contacting site admins.
