### ISSUE TITLE
name4url doesn't cope if there is a querystring

### ISSUE THREAD

**Issue by kewalaka** [majkinetor/au#82]
This is a great piece of work!  I've submitted an automated package for Cryptomator, in doing so found an issue with URLs that have a query string.  e.g.

> https://bintray.com/cryptomator/cryptomator/download_file?file_path=Cryptomator-1.2.3-x64.exe

Can I suggest that an extra line is added after https://github.com/majkinetor/au/blob/master/AU/Public/Get-RemoteFiles.ps1#L43

.. to do something like this

> $res = $res -split '=' -split '&' | where { $_ -match '\\.[a-zA-Z0-9]{3,}' }

That will split the query string and look for the most likely candidate (a string ending in a dot + 3 characters).  I guess you could restrict it to .exe,.msi,.msu, this just seemed better.  It shouldn't impact any existing scenarios as far as I can fathom.

**Comment by majkinetor** [comment]
Why don't you just use `$FileNameBase` argument:

`Get-RemoteFiles -FileNameBase Cryptomator`

or

`Get-RemoteFiles -FileNameBase "Cryptomator-$($Latest.Version)"`

**Comment by kewalaka** [comment]
ah yes, thank you, make sense.
