### ISSUE TITLE
Integrate Set-DescriptionFromReadme

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au#85]

**Comment by AdmiringWorm** [comment]
If this is added, it should probably be added in a way that automatically escapes specific characters  into their xml/http variant(actually easily done by using `InnerText` property I believe), or by wrapping `<description>` inside a `<![CDATA` tag

**Comment by majkinetor** [comment]
Definitely, I was bitten by this number of times.

**Comment by majkinetor** [comment]
That actually is harder then it seems because markdown can contain some html directives so any escape there would render them invalid.

**Comment by majkinetor** [comment]
This is implemented in `automatic_readme` branch and I will merge it when I see how it works on my repo.

I opted for this to be totally automatic by default - if Readme.md is present it will be used unless you specify `NoReadme` to `update`.

**Comment by AdmiringWorm** [comment]
> That actually is harder then it seems because markdown can contain some html directives so any escape there would render them invalid.

Not really that hard, I actually use a helper in my own repository which escapes the necessary invalid xml without much code at all:
https://github.com/AdmiringWorm/chocolatey-packages/blob/master/scripts/Update-Metadata.ps1

> This is implemented in automatic_readme branch and I will merge it when I see how it works on my repo.

awesome

**Comment by majkinetor** [comment]
I added README.md's to few most frequently updated tools so we can check out how it works ASAP.
