### ISSUE TITLE
au_push what does it control?

### ISSUE THREAD

**Issue by riezebosch** [majkinetor/au#87]
I suspect it's to enable/disable `git push` but it could also mean `choco push`.

**Comment by majkinetor** [comment]
To chocholatey as it says in the [comment](https://github.com/majkinetor/au-packages-template/blob/master/update_all.ps1#L13)

**Comment by riezebosch** [comment]
I was looking at the [appveyor.yml](https://github.com/majkinetor/au-packages-template/blob/54d363ed00f5d62a4a05a0229de10531b7b9fbb8/.appveyor.yml#L17).

**Comment by majkinetor** [comment]
Git cred is required on AV. It can work without it locally
