### ISSUE TITLE
Changes on package with deviant packagename not committed

### ISSUE THREAD

**Issue by riezebosch** [majkinetor/au#88]
https://ci.appveyor.com/project/riezebosch/boxstarterpackages/build/156#L132

## My scenario
I have 2 packages for docker-for-windows, on for the stable channel and one for the edge-channel. They both use the same package-id but differ in version number (xx.xx.xx.xx & xx.xx.xx.xx-edge). Therefor I've included the correct package name in the result object of the [au_GetLatest])https://github.com/riezebosch/BoxstarterPackages/blob/master/docker-for-windows-edge/Update.ps1#L22) function.

## Actual behavior
The nuspec is updated correctly, but the changes are not staged for commit.

## Expected behavior
I expect the udpated .nuspec and chocolateyInstall.ps1 to be staged, committed and pushed to my packages repository.

**Comment by majkinetor** [comment]
Fixed in #66 but not yet released. I will release this version during the weekend.

**Comment by riezebosch** [comment]
Thanks for the awesome work.
