### ISSUE TITLE
You cannot call a method on a null-valued expression. ??

### ISSUE THREAD

**Issue by JourneyOver** [majkinetor/au#90]
Dunno exactly what is causing this issue to come up but it's kind of annoying me.

this is the update script I am having issues with
```ps
Import-Module au
Import-Module "$PSScriptRoot\..\..\scripts\au_extensions.psm1"

$releases = 'https://github.com/DuckieTV/Nightlies/releases'

function global:au_SearchReplace {
  @{
    ".\tools\chocolateyInstall.ps1" = @{
      "([$]url\s*=\s*)('.*')"        = "`$1'$($Latest.URL32)'"
      "([$]url64\s*=\s*)('.*')"      = "`$1'$($Latest.URL64)'"
      "([$]checksum\s*=\s*)('.*')"   = "`$1'$($Latest.Checksum32)'"
      "([$]checksum64\s*=\s*)('.*')" = "`$1'$($Latest.Checksum64)'"
    }
  }
}
function global:au_AfterUpdate {
  Set-DescriptionFromReadme -SkipFirst 1
}

function global:au_GetLatest {
  $download_page = Invoke-WebRequest -Uri $releases -UseBasicParsing

  $regex = 'x(\d+).zip$'
  $url = $download_page.links | Where-Object href -match $regex | ForEach-Object href | Select-Object -First 2

  $bversion = $url[0] -split 'nightly-|/' | Select-Object -Last 1 -Skip 1
  $version = $bversion -replace '(....(?!$))', '$1.'
  $build = '-nightly'

  $url32 = 'https://github.com' + $url[0]
  $url64 = 'https://github.com' + $url[1]

  $Latest = @{ PackageName = 'duckietv'; URL32 = $url32; URL64 = $url64; Version = ($version + $build)}
  return $Latest
}

update
```

For some reason whenever I run a test-all or appveyor runs it's stuff it always produces the error "You cannot call a method on a null-valued expression." Currently I'm circumventing this issue by throwing  

```ps
  $userAgent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2;)"
  $32url = "$url32"
  $64url = "$url64"
  $path = "C:\DuckieTV-$bversion-windows-x32.zip"
  $64path = "C:\DuckieTV-$bversion-windows-x64.zip"

  $client = New-Object System.NET.Webclient
  $client.Headers.Add("user-agent", $userAgent)
  $client.DownloadFile( $32url, $path )
  $client.DownloadFile( $64url, $64path )
  $Latest.Checksum32 = Get-FileHash C:\DuckieTV-$bversion-windows-x32.zip | ForEach-Object Hash
  $Latest.Checksum64 = Get-FileHash C:\DuckieTV-$bversion-windows-x64.zip | ForEach-Object Hash
  Remove-Item C:\DuckieTV-$bversion-windows-x32.zip
  Remove-Item C:\DuckieTV-$bversion-windows-x64.zip
```
into the mix in the 'au_GetLatest' stuff and having the update do a -ChecksumFor none which does seem to work alright but I'm wanting to cut it out if possible and make the updater a bit faster.

I have tried to do a 
```ps
function global:au_BeforeUpdate {
  $Latest.Checksum32 = Get-RemoteChecksum $Latest.URL32
  $Latest.Checksum64 = Get-RemoteChecksum $Latest.URL64
}
```
but it seems to take forever, anywhere between 30 minutes to 1+ hours which makes that out of the question big time..

So is there anyway I can get some help on figuring out what is causing this issue?

**Comment by majkinetor** [comment]
So this happens only on test-all ? 

I am not sure why would `Get-RemoteChecksum` take forever, its only 80MB file.

Are you really making nightly packages ? 


Please provide the appveyor build that shows this.

You may choose to embed the zip files - `Get-RemoteFiles` does exactly your code. You can even just use it to get the hash - although the files will be downloaded to \tools you can delete them.

Get-RemoteChecksum is [very simple](https://github.com/majkinetor/au/blob/master/AU/Public/Get-RemoteChecksum.ps1), I don't know why it takes hours for you, especially on AV where it is used extensively in coreteamrepo for embedded packages

**Comment by majkinetor** [comment]
It might be that `-UseBasicParsing` in iwr is what is causing problem with github tho, I experienced it numerous times but never on binaries.

**Comment by JourneyOver** [comment]
> So this happens only on test-all ?

It happens on both normal appveyor builds, test-all appveyor builds, and doing a local test-all, I caught the issue in a appveyor [test-all](https://ci.appveyor.com/project/JourneyOver/chocolatey-packages-khbb9/build/30) run and a [normal](https://ci.appveyor.com/project/JourneyOver/chocolatey-packages/build/120) run.

> I am not sure why would Get-RemoteChecksum take forever, its only 80MB file.

I'm not sure either tbh :/ last run I tried it took 20 minutes to go through both the 32bit and 64bit urls and get the checksums..which is not great at all.. (this is all local as I'm not pushing a new update.ps1 script up until I can get this issue figured out) [update test local](https://gist.github.com/anonymous/9f5fe99b2736ff4c25d7536385541ec4/6dd8e849ec57af499af287e6d737277771b226c0)

> Are you really making nightly packages ?

yea I'm making nightly packages for this program since it has a nightly release lol (and someone asked me to do it for them) >..< everything has been working so far other than the [update script](https://github.com/JourneyOver/chocolatey-packages/blob/master/automatic/duckietv_pre/update.ps1) I'm currently running being a bit slow so I wanted to see if I could get this issue figured out and switch it so it's a bit faster like all my other packages..

> Please provide the appveyor build that shows this.

Provided above. 

> You may choose to embed the zip files - Get-RemoteFiles does exactly your code. You can even just use it to get the hash - although the files will be downloaded to \tools you can delete them.

Would doing something like that be exactly as doing except for putting them in \tools instead of C:\
```ps
 $userAgent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2;)"
  $32url = "$url32"
  $64url = "$url64"
  $path = "C:\DuckieTV-$bversion-windows-x32.zip"
  $64path = "C:\DuckieTV-$bversion-windows-x64.zip"

  $client = New-Object System.NET.Webclient
  $client.Headers.Add("user-agent", $userAgent)
  $client.DownloadFile( $32url, $path )
  $client.DownloadFile( $64url, $64path )
  $Latest.Checksum32 = Get-FileHash C:\DuckieTV-$bversion-windows-x32.zip | ForEach-Object Hash
  $Latest.Checksum64 = Get-FileHash C:\DuckieTV-$bversion-windows-x64.zip | ForEach-Object Hash
  Remove-Item C:\DuckieTV-$bversion-windows-x32.zip
  Remove-Item C:\DuckieTV-$bversion-windows-x64.zip
```
?

> Get-RemoteChecksum is very simple, I don't know why it takes hours for you, especially on AV where it is used extensively in coreteamrepo for embedded packages

tbh idk how long it takes at max, every time I've run a Get-RemoteChecksum test it's always been local on my computer and not on appveyor as the testing always took forever to go through, there was never a moment of testing where it was only a minute or two always 20+ minutes at min (and sometimes I would just cancel it after 10-15 minutes of having it do nothing) so I just never pushed a version up to test it through appveyor completely.

> It might be that -UseBasicParsing in iwr is what is causing problem with github tho, I experienced it numerous times but never on binaries.

Not sure, I tried taking that bit out and running another test-all locally and it produced the same "You cannot call a method on a null-valued expression." error.

**Comment by majkinetor** [comment]
> Would doing something like that be exactly as doing except for putting them in \tools instead of C:\

Yeah, it gets the $Latest.URL32/64, obtains the checksum locally and saves in tools.

>  "You cannot call a method on a null-valued expression."

I don't know what line of AU code returns this issue. It looks like 

```
$fversion = $version.replace('.', '').replace('-nightly', '')
```

is that thing since `$version` doesn't get value from anywhere. If you fix that, I think it will pass. If you still have a problem, try `Get-RemoteFiles` in `au_BeforeUpdate`.

If nothing helps, I will be glad to try it on my own since I discovered few awesome packages in your repository, I am just testing ducky 🥇

**Comment by majkinetor** [comment]
Looks like you have the same version problem in non nightly ducky.

**Comment by JourneyOver** [comment]
The non nightly ducky worked right away through all tests, it never had any issues with test-all.

**Comment by JourneyOver** [comment]
btw I'm going through my stuff in the dev branch so if looking at scripts and such I'd suggest taking a look there instead of the master branch since I haven't pushed anything new to the master branch in a while other than stuff happening from the appveyor builds.

**Comment by majkinetor** [comment]
Thats because daily ducky does things differently, it just gets ignored:

```
$fileLocation = "$env:ChocolateyInstall\lib\$packageName\tools\DuckieTV-$version-windows-x$bits.exe"
```

contrary to that, you have `$veresion.replace()` in night duck which is calling function on null.

You wanted `$env:ChoolateyPackageVersion` ?

**Comment by majkinetor** [comment]
Its the same in your other branch

**Comment by JourneyOver** [comment]
Well that was the issue for ducky nightly, once I added a version variable in it worked :D

dunno why the updater script fails because of that, the install script never failed when installing it, same with the normal ducky package. They both install without issues, ducky nightly had issues with update which seem to be because of the above problem which now seems to be fixed, and ducky normal never had an issue with updates, even if I was to throw a lower version number in the nuspec and then run a test-all.

**Comment by majkinetor** [comment]
Updater fails because automatic checksum runs the chocolateyInstaller to download the package. Your package probably doesn't fail as you don't have `$ErrorActionPreference` set to stop, while AU has it. People usually keep it as a first line in a package installer.

**Comment by majkinetor** [comment]
You have great packages btw, consider embedding them. You will not have problems with automatic checksum and your package will always work.

See https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed for details

**Comment by JourneyOver** [comment]
ahh got it, and yea I'm adding an `$ErrorActionPreference = 'Stop'` to all of my packages on the dev branch along with updating a lot of the other stuff and once all that is done then it'll all be pushed to the master branch, but thanks a lot for helping me out with this problem :)

**Comment by majkinetor** [comment]
No problem at all. Thanks for using AU.

**Comment by JourneyOver** [comment]
Thanks for creating AU hehe :p if it wasn't for AU I probably would of never of really gotten into using chocolatey nor creating packages for it.

**Comment by majkinetor** [comment]
Yeah, me neither :)
