### ISSUE TITLE
Support for multiple software versions

### ISSUE THREAD

**Issue by Thilas** [majkinetor/au#92]
I know this has already been discussed (#56) but I'm not really happy with the provided solution especially because of all the required duplication. I know we are potentially talking about supporting multiple versions that can need different package definitions but there are a lot of cases where a single package can easily handle multiple versions without any overheads.

I have 2 use cases in mind:
1. a maintained branch and a prerelease branch releasing new versions simultaneously (e.g. https://github.com/atom/atom, [package source](https://github.com/Thilas/chocolatey-packages/tree/master/atom))
2. multiple maintained branches (e.g. http://strawberryperl.com/releases.html, [package source](https://github.com/Thilas/chocolatey-packages/tree/master/strawberryperl))

In both cases, I have packages that can handle new versions without having differences in their definitions. And the only thing preventing me from publishing new versions for each branch is the `is_updated` function in [`Update-Package.ps1`](https://github.com/majkinetor/au/blob/86d5fb646d3e1d19a9719c46666f532a8f6641d9/AU/Public/Update-Package.ps1#L265). Because it makes sure the new version is actually newer than the current one (from the nuspec file), it refuses to take it into account.

Then why not adding an optional switch to `Update-Package` in order to skip this logic and replace it by a simple "is new version different from the nuspec version"? Of course, I can provide a PR if you want.

**Comment by majkinetor** [comment]
The relevant discussion is #74.

What you want you can do now by forcing the package update within `au_Update` ([example](https://github.com/majkinetor/au-packages/blob/master/cpu-z.install/update.ps1#L36))

**Comment by Thilas** [comment]
Thanks for the answer! Regarding the workaround, I implemented a variant of it and it solved indeed my cases.

What about #74, it sounds like a good idea. Any progress? Do you need some help with it?

**Comment by majkinetor** [comment]
> Any progress? Do you need some help with it?

To be honest, I have almost 0 motivation for this. I don't keep any multi-stream packages, and few people are. This would mostly benefit coreteampackages-repo which is the largest AU user and already has several streamed packages. Furthermore, my real life job will take almost all my free time until the end of the year. So any help would be appreciated.

**Comment by majkinetor** [comment]
There is also idea here: https://github.com/chocolatey/chocolatey-coreteampackages/issues/812

**Comment by Thilas** [comment]
I don't like much this last idea. Too "manual" to me 😄 

Anyway I understand your situation. I'll think about it, especially to the stream approach discussed in #74.

**Comment by majkinetor** [comment]
The last idea is manual but provides ability to PR any version which is clearly not the case otherwise.

**Comment by Thilas** [comment]
Sure, I see your point.

**Comment by majkinetor** [comment]
Both solutions could co-exist
