### ISSUE TITLE
chocolatey.org is hardcoded

### ISSUE THREAD

**Issue by rismoney** [majkinetor/au#95]
can this be parameterized to point to custom feeds?

**Comment by majkinetor** [comment]
Current string is `"https://chocolatey.org/packages/{0}/{1}" -f PackageName, PackageVersion`

What is your string ?Would this fit your case ? 

```powershell
"$au_ChocolateyUrl/packages/{0}/{1}" -f PackageName, PackageVersion
```

Or there needs to be more robust thing available, not sure if all galleries conform to same API ( /cc @ferventcoder)

**Comment by ferventcoder** [comment]
@majkinetor internal use is likely where @rismoney is using this.

**Comment by majkinetor** [comment]
I suppose so, but is the URL path the same ? Would this suffice:

```powershell
if ( !$au_GalleryUrl ) { $au_GalleryUrl = 'https://chocolatey.org' } 
$choco_url = "$au_GalleryUrl/packages/{0}/{1}" -f $global:Latest.PackageName, $package.RemoteVersion
```

**Comment by ferventcoder** [comment]
@majkinetor that is not an "API" as you describe it. The API is at https://chocolatey.org/api/v2 and all Chocolatey / NuGet v2 sources conform to a similar API for use.

**Comment by rismoney** [comment]
@majkinetor I modified line https://github.com/majkinetor/au/blob/master/AU/Public/Update-Package.ps1#L344 to chocolatey.myco.org/{0}{1} and the software worked.

It might be simply adding a param like [string] $feed="chocolatey.org"

I will work out the second part of the equation this afternoon for the actual url.  Just started learning AU an hour ago.

**Comment by rismoney** [comment]
So the below worked without any other mods to the repo.  I think it _may_ be downloading the bits 2x. Once from the external, and once from the internal. I don't know if i care, but I don't know the path where the bits be going.  I wasn't sure what was up with the monkeys and patching :)


```
import-module au

function global:au_SearchReplace {
    @{
        'tools\chocolateyInstall.ps1' = @{
            "(^\s*url64bit\s*=\s*)('.*')"      = "`$1'$($Latest.internalsite)'"
            "(^\s*checksum64\s*=\s*)('.*')" = "`$1'$($Latest.checksum64)'"
        }
     }
}

function global:au_GetLatest {
    $baseurl = 'https://notepad-plus-plus.org'
    $packagename = "notepadplusplus"
    $chocopackagepath = "D:\chocopackages"
    $download_page = Invoke-WebRequest -Uri ($baseurl + "/download")
    $re      = '/npp..*.Installer.exe'
    $url   = $download_page.links | ? href -match $re | select -First 1 -expand href
    $filename = $URL.Substring($URL.LastIndexOf("/") + 1)
    $version = $url -replace "^.*npp\.([0-9\.]+)\.Installer.exe$", '$1'
    $internalurl = "https://chocopackages.myorg.internal/$packagename"
    Invoke-WebRequest -Uri ($baseurl + $url) -outfile "$chocopackagepath\$packagename\$filename"
    $is = $internalurl + "/" + $filename
    return @{ URL64 = $baseurl + $url; Version = $version ; internalsite = $is }
}

Update-Package -ChecksumFor 64

**Comment by majkinetor** [comment]
> I think it may be downloading the bits 2x. Once from the external, and once from the internal.

It is by default, but you can disable it with `-NoCheckChocoVersion`:

https://github.com/majkinetor/au/blob/86d5fb646d3e1d19a9719c46666f532a8f6641d9/AU/Public/Update-Package.ps1#L74-L76

**Comment by rismoney** [comment]
I'll test that. Thank you.  Going back to original issue https://github.com/majkinetor/au/issues/95#issuecomment-336979924 would suffice.

**Comment by insanity54** [comment]
I too am looking for a way to automatically push a large number of packages to an internal feed. Ideally I would like to be able to add a line to update_vars_default.ps1

```
$Env:au_GalleryUrl    = 'http://nuget.example.com/'
```
